import type { LearningItem } from './types'

export const LEARNING_ITEMS: readonly LearningItem[] = [
  {
    id: 'workspace.drag-terminal-into-workspace',
    title: 'Drag a terminal into a workspace',
    summary: 'Keep an agent session attached to the work it belongs to.',
    body: 'Drag a terminal tab onto another workspace in the sidebar to move the session — its agent, logs, and prompt history travel with it. Use it when a side investigation grows into its own deliverable.',
    category: 'workspace',
    difficulty: 'basic',
    action: { label: 'Open Learn Center', kind: 'open-learn-center' },
  },
  {
    id: 'workspace.drop-file-into-terminal',
    title: 'Drop a file into a terminal',
    summary: 'Hand an agent concrete context without retyping paths.',
    body: 'Drag a file from the file explorer onto a terminal tab. Multicode pastes the absolute path so your agent can read, edit, or run it — no copy/paste shuffling.',
    category: 'workspace',
    difficulty: 'basic',
  },
  {
    id: 'agents.spawn-specialist',
    title: 'Use specialist roles for high-judgment work',
    summary: 'Architecture, frontend, QA, security, performance, and review each have a Soul.',
    body: 'When the task needs judgment beyond a generic chat, spawn a specialist. Each specialist loads a role-specific Soul, picks a sensible CLI runtime, and applies the right permission preset before it starts.',
    category: 'agents',
    difficulty: 'basic',
    action: { label: 'Open Learn Center', kind: 'open-learn-center' },
  },
  {
    id: 'sprintengine.check-evidence',
    title: 'Check evidence before treating a task as done',
    summary: 'Sprint Engine surfaces gate state, attempts, and artifacts in the detail pane.',
    body: 'Open the Sprint Engine board, select a task, and read the Attempts timeline and gate evidence. A green column is not enough — confirm the artifacts the agent produced before you ship.',
    category: 'sprintengine',
    difficulty: 'intermediate',
  },
  {
    id: 'switchboard.watchtower-to-inbox',
    title: 'Turn review findings into Switchboard tasks',
    summary: 'Watchtower promotes review hits into the Switchboard inbox.',
    body: 'When Watchtower finishes a review pass, promote each finding to the Switchboard inbox so it gets ranked and routed like any other task instead of living in a transient run log.',
    category: 'switchboard',
    difficulty: 'intermediate',
  },
  {
    id: 'knowledge.configure-graph-root',
    title: 'Configure the Knowledge Graph',
    summary: 'Give agents product, brand, and architecture context before they edit.',
    body: 'In Settings → Knowledge Graph, point Multicode at a relative folder under your project. Agents will read product, architecture, and brand notes from there before they touch code.',
    category: 'knowledge',
    difficulty: 'basic',
    action: {
      label: 'Open Knowledge Graph settings',
      kind: 'open-settings-tab',
      args: { tab: 'knowledge-graph' },
    },
  },
  {
    id: 'knowledge.install-workspace-skill',
    title: 'Install the workspace-knowledge skill',
    summary: 'Agents need the skill installed before they can read and update your graph.',
    body: 'Once the Knowledge Graph root is set, install the workspace-knowledge built-in skill from the same settings tab. Agents will use it to fetch and update knowledge instead of guessing.',
    category: 'knowledge',
    difficulty: 'basic',
    action: {
      label: 'Open Knowledge Graph settings',
      kind: 'open-settings-tab',
      args: { tab: 'knowledge-graph' },
    },
  },
  {
    id: 'local-safety.prefer-worktrees',
    title: 'Prefer worktrees when agents touch code',
    summary: 'Multiple agents working in parallel should run in their own checkout.',
    body: 'When you spawn an agent, choose the worktree execution mode if any other agent might touch the same branch. Multicode isolates each run so failing experiments do not stomp on each other.',
    category: 'local-safety',
    difficulty: 'intermediate',
  },
  {
    id: 'local-safety.permission-presets',
    title: 'Pick permission presets intentionally',
    summary: 'Default, plan-only, and full-auto change what the agent is allowed to do.',
    body: 'Before you launch a terminal agent, glance at the permission preset chip. Default asks before destructive moves; full-auto skips the prompts. Match the preset to how much you trust the task description.',
    category: 'local-safety',
    difficulty: 'intermediate',
  },
  {
    id: 'local-safety.keep-terminals-visible',
    title: 'Keep terminals visible',
    summary: 'Failed commands and blocked prompts are obvious when the session is on screen.',
    body: 'Drag the relevant terminals into the active workspace layout instead of hiding them behind tabs. Local-first delivery only works when you can see what each agent is doing — and what it is stuck on.',
    category: 'local-safety',
    difficulty: 'basic',
  },
  {
    id: 'workspace.command-palette',
    title: 'Open the command palette',
    summary: 'Most workspace, agent, and settings actions are reachable from one place.',
    body: 'Press ⌘K (Ctrl+K on Windows/Linux) to open the command palette. Spawn agents, switch workspaces, open settings tabs, and jump between layouts without leaving the keyboard.',
    category: 'workspace',
    difficulty: 'basic',
  },
  {
    id: 'workspace.sidebar-toggle',
    title: 'Toggle the sidebar with ⌘B',
    summary: 'Reclaim screen real estate when terminals and editors need room.',
    body: 'Use ⌘B to collapse the workspace sidebar to an icon rail. The rail still shows active workspaces and the running/needs-input dots so you do not lose situational awareness.',
    category: 'workspace',
    difficulty: 'basic',
  },
  {
    id: 'workspace.switch-by-number',
    title: 'Jump straight to a workspace',
    summary: 'Use number shortcuts when several workspaces are open.',
    body: 'Press ⌘1 through ⌘9 to activate the matching workspace in the sidebar. It is faster than cycling when you are comparing a plan, a run, and a review workspace side by side.',
    category: 'workspace',
    difficulty: 'basic',
  },
  {
    id: 'workspace.cycle-layout-tabs',
    title: 'Cycle layout tabs without reaching for the mouse',
    summary: 'Move through open files, panels, and terminals from the keyboard.',
    body: 'Use ⌘Tab and ⌘⇧Tab inside a workspace to move between layout tabs. Use ⌘W to close the active layout tab when you are done with a temporary view.',
    category: 'workspace',
    difficulty: 'basic',
  },
  {
    id: 'workspace.open-file-explorer',
    title: 'Toggle the file explorer',
    summary: 'Bring project files in only when you need source context.',
    body: 'Press ⌘⇧E to show or hide the file explorer. Keep it open while collecting paths for an agent, then collapse it when terminals and review panes need the room.',
    category: 'workspace',
    difficulty: 'basic',
  },
  {
    id: 'workspace.open-plain-terminal',
    title: 'Open a plain terminal quickly',
    summary: 'Use a neutral shell when the task is not agent-specific.',
    body: 'Press ⌘⇧\' to open a plain terminal in the active workspace. Use it for quick git checks, local test commands, or setup steps before handing focused work to an agent.',
    category: 'workspace',
    difficulty: 'basic',
  },
  {
    id: 'agents.nuclear-reviewer',
    title: 'Use Nuclear Reviewer for maintainability audits',
    summary: 'Separate "does it work" from "should this shape ship."',
    body: 'Spawn the Nuclear Reviewer when a change feels too broad, abstract, or AI-generated. It reviews structure, maintainability, fake affordances, and long-term code health instead of only checking correctness.',
    category: 'agents',
    difficulty: 'intermediate',
  },
  {
    id: 'agents.bind-specialist-cli-defaults',
    title: 'Set specialist CLI defaults once',
    summary: 'Avoid reselecting the same runtime for recurring roles.',
    body: 'Use the agent picker chip or Settings → Agents to keep each specialist role on the CLI that suits it best. Multicode stores those defaults separately from the last general-purpose CLI.',
    category: 'agents',
    difficulty: 'basic',
    action: {
      label: 'Open Agents settings',
      kind: 'open-settings-tab',
      args: { tab: 'agents' },
    },
  },
  {
    id: 'guided-brief.full-brief-before-build',
    title: 'Start with the Design Wizard when the shape is fuzzy',
    summary: 'Strategist, architect, and designer sessions turn an idea into build context.',
    body: 'Use the Design Wizard before running a sprint when the product goal, architecture, or UI direction still needs discovery. Accepting the plan creates a real handoff package instead of relying on chat history.',
    category: 'guided-brief',
    difficulty: 'basic',
    showWhen: [{ kind: 'workspace-mode', value: 'guided-brief' }],
  },
  {
    id: 'guided-brief.design-studio-preview',
    title: 'Preview Design only artifacts in place',
    summary: 'The design-only mode keeps files, preview, and designer terminal together.',
    body: 'In Design only mode, use the Design Files pane to choose a generated artifact and the Preview pane to inspect it. HTML mockups render in the workspace so you can review the actual file before accepting it.',
    category: 'guided-brief',
    difficulty: 'basic',
    showWhen: [{ kind: 'workspace-mode', value: 'guided-brief' }],
  },
  {
    id: 'guided-brief.accepted-build-handoff',
    title: 'Accept only real plan artifacts',
    summary: 'Sprint handoff depends on files, not vibes.',
    body: 'Before starting a build from the Design Wizard, check that the accepted plan, UI direction, and mockup files say what you want. Those files become the source bundle sprint agents receive.',
    category: 'guided-brief',
    difficulty: 'intermediate',
    showWhen: [{ kind: 'workspace-mode', value: 'guided-brief' }],
  },
  {
    id: 'sprintengine.automation-mode',
    title: 'Choose sprint automation mode deliberately',
    summary: 'Manual, run-agents, and approve-artifacts modes change operator control.',
    body: 'Click the runtime-status chip in the board chrome before a run and check the selected automation mode. Manual keeps you in control; higher automation can spawn agents and, when explicitly selected, approve artifacts.',
    category: 'sprintengine',
    difficulty: 'intermediate',
    showWhen: [{ kind: 'workspace-mode', value: 'sprintengine' }],
  },
  {
    id: 'sprintengine.runtime-status',
    title: 'Read runtime status separately from desired mode',
    summary: 'A run can be configured for automation but paused, blocked, failed, or complete.',
    body: 'When the sprint stops, look at the runtime status message before toggling modes. Resume and retry are for runtime state; switching to Manual changes the operator intent.',
    category: 'sprintengine',
    difficulty: 'intermediate',
    showWhen: [{ kind: 'workspace-mode', value: 'sprintengine' }],
  },
  {
    id: 'sprintengine.graph-and-kanban',
    title: 'Use Graph and Kanban for different questions',
    summary: 'Graph explains dependencies; Kanban explains phase load.',
    body: 'Press G then G for the task graph when you need to understand blockers and ordering. Press G then K when you need a compact phase view of what is ready, in review, in testing, or done.',
    category: 'sprintengine',
    difficulty: 'basic',
    showWhen: [{ kind: 'workspace-mode', value: 'sprintengine' }],
  },
  {
    id: 'sprintengine.roster-before-gates',
    title: 'Check the team before requesting gates',
    summary: 'A missing role can turn review or testing into an unclaimable queue.',
    body: 'Open the Agents view before requesting plan reviews or adding quality gates. Sprint Engine preserves custom gate ids, but each required phase still needs a matching enabled role to claim the work.',
    category: 'sprintengine',
    difficulty: 'advanced',
    showWhen: [{ kind: 'workspace-mode', value: 'sprintengine' }],
  },
  {
    id: 'sprintengine.needs-input-kind',
    title: 'Read the needs-input kind',
    summary: 'Blocked tasks tell you who needs to act next.',
    body: 'A needs-input task may need the architect, user, owner, or external validation. Read the kind, question, and suggested resolution in the inspector before waking the wrong agent.',
    category: 'sprintengine',
    difficulty: 'intermediate',
    showWhen: [{ kind: 'workspace-mode', value: 'sprintengine' }],
  },
  {
    id: 'switchboard.import-external-issues',
    title: 'Import GitHub or Jira issues through Watchtower',
    summary: 'External issues enter the same inbox triage flow as review findings.',
    body: 'In a Switchboard workspace, expand Watchtower\'s Fetch external section to import GitHub or Jira issues. Review them in the inbox before promoting accepted work to the board.',
    category: 'switchboard',
    difficulty: 'basic',
    showWhen: [{ kind: 'workspace-mode', value: 'switchboard' }],
  },
  {
    id: 'switchboard.runner-queues',
    title: 'Use the Switchboard runner for queued board work',
    summary: 'Ready, testing, and review queues can be executed through the local runner.',
    body: 'Open the Switchboard runner when board tasks are ready for execution or gate work. Runner state is file-backed under the Switchboard store, so do not treat a renderer-only view as the source of truth.',
    category: 'switchboard',
    difficulty: 'intermediate',
    showWhen: [{ kind: 'workspace-mode', value: 'switchboard' }],
  },
  {
    id: 'switchboard.one-store-per-project',
    title: 'Use one Switchboard per project folder',
    summary: 'Duplicate workspace records are avoided so local task state stays clear.',
    body: 'When you create a Switchboard for a folder that already has one, Multicode focuses the existing workspace. Model subdivisions as filters, labels, sources, queues, or milestones instead of separate stores.',
    category: 'switchboard',
    difficulty: 'intermediate',
    showWhen: [{ kind: 'workspace-mode', value: 'switchboard' }],
  },
  {
    id: 'switchboard.watchtower-presets',
    title: 'Pick the Watchtower preset that matches the review',
    summary: 'Lean code, UI/brand, performance, security, and full product reviews launch different specialist mixes.',
    body: 'Use a focused Watchtower preset when you know the risk area. A UI and brand alignment run should read project brand guidance; a security run should not spend its budget on general polish.',
    category: 'switchboard',
    difficulty: 'basic',
    showWhen: [{ kind: 'workspace-mode', value: 'switchboard' }],
  },
  {
    id: 'git.open-log-graph',
    title: 'Use the Git Log graph for branch shape',
    summary: 'The Log tab shows all refs with a lane graph and HEAD marker.',
    body: 'Open the Git panel and switch to Log when branch relationships matter. The graph uses position and labels for branch identity, with the accent reserved for HEAD and selected ancestry.',
    category: 'git',
    difficulty: 'basic',
  },
  {
    id: 'git.commit-actions-menu',
    title: 'Use commit row actions for safe branch moves',
    summary: 'Checkout, branch, tag, copy, and GitHub actions live on each commit row.',
    body: 'Hover or right-click a commit in the Git Log view to open its actions. Dirty tracked trees block checkout, and history-rewriting actions are intentionally not part of the first menu.',
    category: 'git',
    difficulty: 'intermediate',
  },
  {
    id: 'git.manage-worktrees',
    title: 'Manage worktrees from the Git panel',
    summary: 'Worktrees are the cleanest way to isolate parallel implementation runs.',
    body: 'Use Git: Manage Worktrees from the command palette or Git panel when several agents need code access. Keep experimental or risky work out of the main checkout until it is ready.',
    category: 'git',
    difficulty: 'intermediate',
  },
  {
    id: 'settings.customize-shortcuts',
    title: 'Customize shortcuts from Settings',
    summary: 'Every command row shows its effective keybinding and conflicts.',
    body: 'Open Settings → Shortcuts to search commands, record new chords, remove a binding, or reset defaults. Conflicts are shown inline and use the same command registry as the dispatcher.',
    category: 'settings',
    difficulty: 'basic',
    action: {
      label: 'Open Shortcuts settings',
      kind: 'open-settings-tab',
      args: { tab: 'shortcuts' },
    },
  },
  {
    id: 'settings.enable-modules',
    title: 'Enable only the modules you use',
    summary: 'Optional surfaces such as voice dictation are module-gated.',
    body: 'Use Settings → Modules to enable or disable bundled capabilities. Disabled modules disappear from commands and surfaces instead of leaving inactive controls around the app.',
    category: 'settings',
    difficulty: 'basic',
    action: {
      label: 'Open Modules settings',
      kind: 'open-settings-tab',
      args: { tab: 'modules' },
    },
  },
  {
    id: 'settings.configure-providers',
    title: 'Keep model providers separate from agent CLIs',
    summary: 'Providers store API keys; Agents configure launchable terminal runtimes.',
    body: 'Use Settings → Providers for model and harness credentials. Use Settings → Agents for installed CLI commands. Keeping those separate avoids treating raw APIs as runnable terminal agents.',
    category: 'settings',
    difficulty: 'intermediate',
    action: {
      label: 'Open Providers settings',
      kind: 'open-settings-tab',
      args: { tab: 'providers' },
    },
  },
  {
    id: 'settings.sync-mcps',
    title: 'Sync MCP servers explicitly',
    summary: 'MCP catalog changes do not rewrite existing terminal sessions.',
    body: 'Open Extensions to install bundled or custom MCP servers and sync selected client configs. Restart or respawn agent sessions that need a newly synced tool.',
    category: 'settings',
    difficulty: 'intermediate',
    action: {
      label: 'Open Extensions',
      kind: 'open-settings-tab',
      args: { tab: 'mcps' },
    },
  },
  {
    id: 'settings.install-skill-packs',
    title: 'Install skill packs before expecting agents to use them',
    summary: 'Skill pack state is local app configuration.',
    body: 'Open Extensions to install bundled or ecosystem skill packs for supported harnesses. Installed state helps this app configure agents; it is not proof another checkout has the same pack.',
    category: 'settings',
    difficulty: 'basic',
    action: {
      label: 'Open Extensions',
      kind: 'open-settings-tab',
      args: { tab: 'skill-packs' },
    },
  },
  {
    id: 'settings.voice-dictation',
    title: 'Configure voice dictation before using the mic',
    summary: 'Dictation sends audio to a Multivoice transcription host and copies text back.',
    body: 'Use Settings → Voice dictation to set the server URL, model, language, and optional token. Then press ⌘⇧1 or the top-bar mic to record and copy the transcription to your clipboard.',
    category: 'settings',
    difficulty: 'basic',
    action: {
      label: 'Open Voice settings',
      kind: 'open-settings-tab',
      args: { tab: 'voice-dictation' },
    },
  },
  {
    id: 'mobile.pair-companion',
    title: 'Pair the mobile companion from desktop',
    summary: 'Desktop remains the authority for relay and command execution.',
    body: 'Use Settings → Mobile to enable companion control, set the relay URL, request a pairing code, and revoke paired phones. Mobile asks; desktop validates and executes through local product boundaries.',
    category: 'mobile',
    difficulty: 'basic',
    action: {
      label: 'Open Mobile settings',
      kind: 'open-settings-tab',
      args: { tab: 'mobile' },
    },
  },
  {
    id: 'mobile.check-command-diagnostics',
    title: 'Check mobile command diagnostics',
    summary: 'Relay status, capabilities, and recent commands are visible in Settings.',
    body: 'If a phone action does not appear to run, open Settings → Mobile and read the relay/session status and recent command list before retrying. The bridge should fail visibly instead of pretending a command succeeded.',
    category: 'mobile',
    difficulty: 'intermediate',
    action: {
      label: 'Open Mobile settings',
      kind: 'open-settings-tab',
      args: { tab: 'mobile' },
    },
  },
] as const

export function getLearningItemById(id: string): LearningItem | undefined {
  return LEARNING_ITEMS.find((item) => item.id === id)
}

function assertUniqueLearningIds(): void {
  const seen = new Set<string>()
  for (const item of LEARNING_ITEMS) {
    if (seen.has(item.id)) {
      // eslint-disable-next-line no-console
      console.warn(`[learning] duplicate id: ${item.id}`)
    }
    seen.add(item.id)
  }
}

assertUniqueLearningIds()
