export const MULTICODE_SAFE_MODE = import.meta.env.VITE_MULTICODE_SAFE_MODE === '1'
export const MULTICODE_DISABLE_SWARM_AUTORUN =
  MULTICODE_SAFE_MODE || import.meta.env.VITE_MULTICODE_DISABLE_SWARM_AUTORUN === '1'
export const MULTICODE_DISABLE_SWARM_SYNC =
  MULTICODE_SAFE_MODE || import.meta.env.VITE_MULTICODE_DISABLE_SWARM_SYNC === '1'
export const MULTICODE_DISABLE_SWARM_TERMINALS =
  MULTICODE_SAFE_MODE || import.meta.env.VITE_MULTICODE_DISABLE_SWARM_TERMINALS === '1'
