export const SAFE_MODE = import.meta.env.VITE_SPRINTENGINE_SAFE_MODE === '1'
export const DISABLE_SPRINTENGINE_AUTORUN =
  SAFE_MODE || import.meta.env.VITE_SPRINTENGINE_DISABLE_AUTORUN === '1'
export const DISABLE_SPRINTENGINE_SYNC =
  SAFE_MODE || import.meta.env.VITE_SPRINTENGINE_DISABLE_SYNC === '1'
export const DISABLE_SPRINTENGINE_TERMINALS =
  SAFE_MODE || import.meta.env.VITE_SPRINTENGINE_DISABLE_TERMINALS === '1'
