export const MULTICODE_SAFE_MODE = import.meta.env.VITE_MULTICODE_SAFE_MODE === '1'
export const MULTICODE_DISABLE_SPRINTENGINE_AUTORUN =
  MULTICODE_SAFE_MODE || import.meta.env.VITE_MULTICODE_DISABLE_SPRINTENGINE_AUTORUN === '1'
export const MULTICODE_DISABLE_SPRINTENGINE_SYNC =
  MULTICODE_SAFE_MODE || import.meta.env.VITE_MULTICODE_DISABLE_SPRINTENGINE_SYNC === '1'
export const MULTICODE_DISABLE_SPRINTENGINE_TERMINALS =
  MULTICODE_SAFE_MODE || import.meta.env.VITE_MULTICODE_DISABLE_SPRINTENGINE_TERMINALS === '1'
