import type {
  SwarmRole,
  SwarmRoleCounts,
  SwarmRuntimeAgent,
  SwarmState,
} from '../types/workspace'
import {
  buildSwarmAgentRoster,
  createDefaultSwarmRoleCounts,
  normalizeSwarmState,
} from './swarm'

function joinPath(basePath: string, child: string): string {
  const sep = basePath.includes('\\') && !basePath.includes('/') ? '\\' : '/'
  return `${basePath.replace(/[\\/]+$/, '')}${sep}${child}`
}

export function slugifySwarmName(name: string | null | undefined): string {
  const slug = (name ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return slug || 'swarm-team'
}

export function getSwarmRootDirectoryPath(folderPath: string): string {
  return joinPath(folderPath, 'swarm')
}

export function getSwarmDirectoryPath(folderPath: string, swarmName?: string): string {
  return joinPath(getSwarmRootDirectoryPath(folderPath), slugifySwarmName(swarmName))
}

export function getSwarmStateFilePath(folderPath: string, swarmName?: string): string {
  return joinPath(getSwarmDirectoryPath(folderPath, swarmName), 'state.yaml')
}

export function getSwarmPlanFilePath(folderPath: string, swarmName?: string): string {
  return joinPath(getSwarmDirectoryPath(folderPath, swarmName), 'plan.md')
}

export function getSwarmTasksTemplateFilePath(folderPath: string, swarmName?: string): string {
  return joinPath(getSwarmDirectoryPath(folderPath, swarmName), 'tasks.template.json')
}

export function getSwarmTasksSchemaFilePath(folderPath: string, swarmName?: string): string {
  return joinPath(getSwarmDirectoryPath(folderPath, swarmName), 'tasks.schema.json')
}

function isSwarmRole(value: unknown): value is SwarmRole {
  return ['architect', 'product', 'developer', 'frontend', 'tester', 'security'].includes(value as string)
}

function countRolesFromAgents(agents: Record<string, { role: SwarmRole }> | undefined): SwarmRoleCounts | null {
  if (!agents) return null
  const counts = createDefaultSwarmRoleCounts()
  for (const key of Object.keys(counts) as SwarmRole[]) counts[key] = 0
  for (const agent of Object.values(agents)) {
    if (isSwarmRole(agent?.role)) counts[agent.role] += 1
  }
  return Object.values(counts).some((c) => c > 0) ? counts : null
}

export function serializeSwarmStateFile(args: {
  workspaceId: string
  workspacePath: string
  swarmState: SwarmState
}): string {
  const { workspaceId, swarmState } = args
  const notice = 'DO NOT EDIT THIS FILE DIRECTLY. All updates must go through the swarm tool (swarm task status, swarm task log, swarm plan set, etc.). Direct edits will be overwritten and may corrupt swarm state.'
  const output = {
    _notice: notice,
    version: 1,
    swarm: {
      id: `swarm-${workspaceId}-${slugifySwarmName(swarmState.name)}`,
      name: swarmState.name,
      goal: swarmState.goal,
      planApproved: swarmState.planApproved,
      planReady: swarmState.planReady,
      planReadyAt: swarmState.planReadyAt,
      planReadyBy: swarmState.planReadyBy,
      taskGraphReplacedAt: swarmState.taskGraphReplacedAt,
      taskValidation: swarmState.taskValidation,
      updatedAt: new Date().toISOString(),
    },
    agents: swarmState.swarmAgents,
    tasks: swarmState.tasks,
    events: swarmState.events,
  }
  return `${JSON.stringify(output, null, 2)}\n`
}

export function parseSwarmStateFile(content: string): SwarmState {
  const parsed = JSON.parse(content) as Record<string, unknown>
  const swarm = (parsed.swarm ?? {}) as Record<string, unknown>
  const agents = (parsed.agents ?? {}) as Record<string, SwarmRuntimeAgent>
  const roleCounts = countRolesFromAgents(agents) ?? createDefaultSwarmRoleCounts()

  const candidate: SwarmState = {
    name: (swarm.name as string) ?? 'Swarm Team',
    goal: (swarm.goal as string) ?? '',
    roleCounts,
    swarmAgents: Object.keys(agents).length > 0
      ? agents
      : Object.fromEntries(buildSwarmAgentRoster(roleCounts).map((a) => [a.id, { role: a.role, status: 'idle' as const, currentTaskId: null }])),
    planApproved: Boolean(swarm.planApproved),
    planReady: Boolean(swarm.planReady),
    planReadyAt: (swarm.planReadyAt as string | null) ?? null,
    planReadyBy: (swarm.planReadyBy as string | null) ?? null,
    taskGraphReplacedAt: (swarm.taskGraphReplacedAt as string | null) ?? null,
    taskValidation: (swarm.taskValidation as SwarmState['taskValidation']) ?? null,
    events: Array.isArray(parsed.events) ? parsed.events as SwarmState['events'] : [],
    tasks: Array.isArray(parsed.tasks) ? parsed.tasks as SwarmState['tasks'] : [],
  }

  return normalizeSwarmState(candidate) ?? candidate
}

export function serializeSwarmTasksTemplate(): string {
  return `${JSON.stringify({
    tasks: [
      {
        id: 'T1',
        title: 'Replace with a low-level task title',
        description: 'Explain the exact outcome this specialist should deliver.',
        role: 'developer',
        status: 'todo',
        ownerAgentId: null,
        dependsOn: [],
        ownedPaths: ['src/path-or-directory'],
        acceptanceCriteria: ['Specific behavior or outcome that must be true when this task is complete.'],
        implementationNotes: ['Important plan details, constraints, or suggested approach from the architect.'],
        evidence: { summary: '', touchedFiles: [], commandsRan: [], results: [] },
        notes: [],
        startedAt: null,
        completedAt: null,
      },
    ],
  }, null, 2)}\n`
}

export function serializeSwarmTasksSchema(): string {
  return `${JSON.stringify({
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'Swarm Kanban Tasks',
    type: 'object',
    required: ['tasks'],
    additionalProperties: false,
    properties: {
      tasks: {
        type: 'array',
        minItems: 1,
        items: {
          type: 'object',
          required: ['id', 'title', 'description', 'role', 'dependsOn', 'ownedPaths', 'acceptanceCriteria'],
          additionalProperties: true,
          properties: {
            id: { type: 'string', minLength: 1 },
            title: { type: 'string', minLength: 1 },
            description: { type: 'string', minLength: 1 },
            role: { type: 'string', enum: ['architect', 'product', 'developer', 'frontend', 'tester', 'security'] },
            status: { type: 'string', enum: ['todo', 'in_progress', 'needs_input', 'done'], default: 'todo' },
            ownerAgentId: { type: ['string', 'null'] },
            dependsOn: { type: 'array', items: { type: 'string' } },
            ownedPaths: { type: 'array', items: { type: 'string' } },
            acceptanceCriteria: { type: 'array', items: { type: 'string' } },
            implementationNotes: { type: 'array', items: { type: 'string' } },
            evidence: {
              type: 'object',
              properties: {
                summary: { type: 'string' },
                touchedFiles: { type: 'array', items: { type: 'string' } },
                commandsRan: { type: 'array', items: { type: 'string' } },
                results: { type: 'array', items: { type: 'string' } },
              },
            },
            notes: { type: 'array', items: { type: 'string' } },
            startedAt: { type: ['string', 'null'] },
            completedAt: { type: ['string', 'null'] },
          },
        },
      },
    },
  }, null, 2)}\n`
}
