import type {
  SwarmRole,
  SwarmRoleCounts,
  SwarmRuntimeAgent,
  SwarmState,
} from '../types/workspace'
import {
  buildSwarmAgentRoster,
  createDefaultSwarmRoleCounts,
  normalizeSwarmState,
} from './swarm'

function joinPath(basePath: string, child: string): string {
  const sep = basePath.includes('\\') && !basePath.includes('/') ? '\\' : '/'
  return `${basePath.replace(/[\\/]+$/, '')}${sep}${child}`
}

export function slugifySwarmName(name: string | null | undefined): string {
  const slug = (name ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return slug || 'swarm-team'
}

export function getSwarmRootDirectoryPath(folderPath: string): string {
  return joinPath(folderPath, 'swarm')
}

export function getSwarmDirectoryPath(folderPath: string, swarmName?: string): string {
  return joinPath(getSwarmRootDirectoryPath(folderPath), slugifySwarmName(swarmName))
}

export function getExistingSwarmStateFilePath(folderPath: string, swarmDirectoryName: string): string {
  return joinPath(joinPath(getSwarmRootDirectoryPath(folderPath), swarmDirectoryName), 'state.yaml')
}

export function getSwarmStateFilePath(folderPath: string, swarmName?: string): string {
  return joinPath(getSwarmDirectoryPath(folderPath, swarmName), 'state.yaml')
}

export function getSwarmPlanFilePath(folderPath: string, swarmName?: string): string {
  return joinPath(getSwarmDirectoryPath(folderPath, swarmName), 'plan.md')
}

function isSwarmRole(value: unknown): value is SwarmRole {
  return ['architect', 'product', 'developer', 'frontend', 'tester', 'security'].includes(value as string)
}

function countRolesFromAgents(agents: Record<string, { role: SwarmRole }> | undefined): SwarmRoleCounts | null {
  if (!agents) return null
  const counts = createDefaultSwarmRoleCounts()
  for (const key of Object.keys(counts) as SwarmRole[]) counts[key] = 0
  for (const agent of Object.values(agents)) {
    if (isSwarmRole(agent?.role)) counts[agent.role] += 1
  }
  return Object.values(counts).some((c) => c > 0) ? counts : null
}

export function serializeSwarmStateFile(args: {
  workspaceId: string
  workspacePath: string
  swarmState: SwarmState
}): string {
  const { workspaceId, swarmState } = args
  const notice = 'DO NOT EDIT THIS FILE DIRECTLY. All updates must go through the swarm tool (swarm plan add-task, swarm task status, swarm task log, etc.). Direct edits will be overwritten and may corrupt swarm state.'
  const output = {
    _notice: notice,
    version: 1,
    swarm: {
      id: `swarm-${workspaceId}-${slugifySwarmName(swarmState.name)}`,
      name: swarmState.name,
      goal: swarmState.goal,
      updatedAt: new Date().toISOString(),
    },
    agents: swarmState.swarmAgents,
    tasks: swarmState.tasks,
    events: swarmState.events,
  }
  return `${JSON.stringify(output, null, 2)}\n`
}

export function parseSwarmStateFile(content: string): SwarmState {
  const parsed = JSON.parse(content) as Record<string, unknown>
  const swarm = (parsed.swarm ?? {}) as Record<string, unknown>
  const agents = (parsed.agents ?? {}) as Record<string, SwarmRuntimeAgent>
  const roleCounts = countRolesFromAgents(agents) ?? createDefaultSwarmRoleCounts()

  const candidate: SwarmState = {
    name: (swarm.name as string) ?? 'Swarm Team',
    goal: (swarm.goal as string) ?? '',
    roleCounts,
    swarmAgents: Object.keys(agents).length > 0
      ? agents
      : Object.fromEntries(buildSwarmAgentRoster(roleCounts).map((a) => [a.id, { role: a.role, status: 'idle' as const, currentTaskId: null }])),
    events: Array.isArray(parsed.events) ? parsed.events as SwarmState['events'] : [],
    tasks: Array.isArray(parsed.tasks) ? parsed.tasks as SwarmState['tasks'] : [],
  }

  return normalizeSwarmState(candidate) ?? candidate
}
