// The SprintEngine frond — the mark the mobile app wears as its application
// icon. The geometry is the generated one, copied path-for-path from
// `multicode-mobile/sprintengine/simple/mark-light.svg` (built by that repo's
// `mark.js`), so the two products carry the same mark rather than two drawings
// of the same idea. Regenerate there and re-copy; nothing here re-derives it.
//
// Two tones, because the mark has two jobs:
//
//   `brand` keeps the frond's own colors — ink stem and leaflets with the one
//   rust leaflet the mark is built around. It is for the icon chip, which is
//   deliberately a light plate in every theme (see `--icon-chip-bg`), so the
//   ink reads there on light and dark alike.
//
//   `current` is the same frond in `currentColor`, for app chrome that colors
//   its own glyphs — a baked ink would go invisible against half the themes.
//
// No store, no module registry: this file is imported by pure render surfaces
// (the Skills and MCPs aside among them) whose tests mount them without either.

import React, { type JSX } from 'react'

// The mark's own two colors. A brand mark is not themed — these are the values
// the mobile app's generator emits, and the plate it sits on is fixed light for
// exactly this reason. (The marker has to sit within two lines of the value it
// exempts, so it repeats on each rather than heading the paragraph.)
// design-tokens-allow: brand mark ink, generated by the mobile brand kit
const FROND_INK = '#242818'
// design-tokens-allow: brand mark accent leaflet, generated by the mobile brand kit
const FROND_ACCENT = '#b04428'

// The mark's own bounds inside the 1024 square its generator emits, plus a
// hair of padding. The generated file centres a portrait frond in a square with
// a wide empty margin either side — right for an application icon, which is
// mounted in a rounded tile, and wrong for a 22px chip or a 13px chrome glyph,
// where that margin is spent shrinking the mark instead of drawing it. Cropping
// to the frond lets it fill the height of whatever box it is given; the geometry
// itself is untouched.
const FROND_BOX = '237 50 554 816'

/** The stem, then the leaflets in pairs from the base up. */
const STEM = 'M 303.12,855.85 Q 513.01,552.31 685.38,225.33 L 667.88,214.39 Q 487.06,536.09 268.74,834.36 Z'
const ACCENT_LEAFLET =
  'M 344.38,730.89 C 380.75,639.47 345.63,517.00 246.83,390.71 C 229.97,550.17 265.09,672.63 344.38,730.89 Z'
const LEAFLETS = [
  'M 362.96,742.50 C 450.08,788.23 575.55,766.11 711.48,681.05 C 554.66,647.61 429.19,669.74 362.96,742.50 Z',
  'M 453.77,555.82 C 482.57,483.44 454.77,386.49 376.55,286.51 C 363.20,412.75 391.00,509.70 453.77,555.82 Z',
  'M 472.36,567.43 C 541.33,603.64 640.66,586.12 748.27,518.78 C 624.12,492.31 524.79,509.83 472.36,567.43 Z',
  'M 555.36,393.26 C 576.95,338.97 556.10,266.26 497.44,191.27 C 487.43,285.95 508.28,358.67 555.36,393.26 Z',
  'M 573.94,404.87 C 625.67,432.02 700.17,418.89 780.87,368.38 C 687.76,348.53 613.26,361.66 573.94,404.87 Z',
  'M 682.49,210.48 C 733.13,196.22 766.89,142.20 776.26,60.42 C 706.86,104.69 673.11,158.71 682.49,210.48 Z',
]

export function SprintEngineFrond({
  className,
  tone = 'brand',
}: {
  className?: string
  tone?: 'brand' | 'current'
}): JSX.Element {
  const ink = tone === 'brand' ? FROND_INK : 'currentColor'
  const accent = tone === 'brand' ? FROND_ACCENT : 'currentColor'
  return (
    <svg className={className} viewBox={FROND_BOX} fill="none" aria-hidden="true">
      <path d={STEM} fill={ink} />
      <path d={ACCENT_LEAFLET} fill={accent} />
      {LEAFLETS.map((d) => (
        <path key={d} d={d} fill={ink} />
      ))}
    </svg>
  )
}

export default SprintEngineFrond
