// Build identity for the two halves of the app (MC-2182).
//
// Main and the renderer are separate bundles with separate lifetimes. In a
// from-source dev run the renderer hot-reloads out of `src/renderer` while main
// keeps running the bundle it booted with, so delivering into the working tree
// the app is running from (an unattended automated merge into `main`) can leave
// the halves on different commits with no signal at all. Every IPC contract
// that crosses the boundary is exposed to that, not just one surface.
//
// So each bundle carries a stamp minted when it was built, and main compares its
// own against the one every window reports. The identity is the git commit: a
// dirty working tree is the normal dev loop and must not raise anything, while a
// merge moves HEAD and is exactly the hazard. The stamp is generated by the
// `multicode-build-stamp` plugin in `electron.vite.config.ts` and reaches both
// bundles as `virtual:multicode-build-stamp`.

/** Fire-and-forget channel a window reports its own stamp on. */
export const BUILD_STAMP_CHANNEL = 'app:build-stamp'

/**
 * Log prefix for everything this comparison emits. A skew is structural — it
 * does not clear on its own and no retry helps — so it must be greppable apart
 * from the transient timeouts an operator (or an agent reading logs) should
 * retry instead.
 */
export const BUILD_SKEW_LOG_PREFIX = '[build-skew]'

/** Stable code on the machine-readable line, for the same reason. */
export const BUILD_SKEW_CODE = 'build_skew_detected'

type BuildStampSource = 'git' | 'unavailable'

export type BuildStamp = {
  /** Full commit sha the bundle was built from; null when git could not answer. */
  commit: string | null
  source: BuildStampSource
  /** ISO 8601, when this bundle's stamp was minted. */
  builtAt: string
  mode: 'development' | 'production'
}

export type BuildSkewVerdict =
  | { status: 'match' }
  | { status: 'skew' }
  /** No commit on one side (a source tarball, git absent) — unknowns are not compared. */
  | { status: 'indeterminate'; missing: 'main' | 'renderer' | 'both' }

export function compareBuildStamps(main: BuildStamp, renderer: BuildStamp): BuildSkewVerdict {
  if (!main.commit && !renderer.commit) return { status: 'indeterminate', missing: 'both' }
  if (!main.commit) return { status: 'indeterminate', missing: 'main' }
  if (!renderer.commit) return { status: 'indeterminate', missing: 'renderer' }
  return main.commit === renderer.commit ? { status: 'match' } : { status: 'skew' }
}

export function shortCommit(commit: string | null): string {
  return commit ? commit.slice(0, 7) : 'unknown'
}

/**
 * Rejects anything that is not a stamp rather than coercing it. A window that
 * reports garbage is a bug to see, not a comparison to guess at.
 */
export function parseBuildStamp(value: unknown): BuildStamp | null {
  if (!value || typeof value !== 'object') return null
  const candidate = value as Record<string, unknown>
  const commit = candidate['commit']
  const source = candidate['source']
  const builtAt = candidate['builtAt']
  const mode = candidate['mode']
  if (commit !== null && typeof commit !== 'string') return null
  if (source !== 'git' && source !== 'unavailable') return null
  if (typeof builtAt !== 'string') return null
  if (mode !== 'development' && mode !== 'production') return null
  return { commit: commit ?? null, source, builtAt, mode }
}

/** One line, machine-readable, for the log scraper and the agent reading it. */
export function formatBuildSkewLogLine(main: BuildStamp, renderer: BuildStamp): string {
  return (
    `${BUILD_SKEW_LOG_PREFIX} ${BUILD_SKEW_CODE} main=${shortCommit(main.commit)} ` +
    `renderer=${shortCommit(renderer.commit)} resolution=restart_required transient=false`
  )
}

/** Headline + helper line, for the one notice a person sees. */
export function formatBuildSkewNotice(main: BuildStamp, renderer: BuildStamp): { headline: string; detail: string } {
  return {
    headline: 'Main and window are running different builds.',
    detail:
      `Main process: ${shortCommit(main.commit)}, built ${main.builtAt}. ` +
      `Window: ${shortCommit(renderer.commit)}, built ${renderer.builtAt}. ` +
      'The working tree changed under the running app, so the window reloaded onto another ' +
      'commit and main did not. Restart Multicode — anything crossing the two can disagree until you do.',
  }
}
