// Generated from sprintengine_mcp/schemas.py — do not edit.
// Regenerate: python3 scripts/generate_sprintengine_tool_names.py

export const SPRINTENGINE_TOOL_NAMES = [
  'sprintengine.agent.heartbeat',
  'sprintengine.agent.join',
  'sprintengine.agent.leave',
  'sprintengine.agent.next_directive',
  'sprintengine.artifact.add',
  'sprintengine.artifact.approve',
  'sprintengine.artifact.list',
  'sprintengine.artifact.ready',
  'sprintengine.artifact.request_changes',
  'sprintengine.dispatch.ack',
  'sprintengine.dispatch.next',
  'sprintengine.feedback.recommend_actions',
  'sprintengine.feedback.summarize',
  'sprintengine.gate.claim',
  'sprintengine.gate.list',
  'sprintengine.gate.next',
  'sprintengine.gate.verdict',
  'sprintengine.handover',
  'sprintengine.health',
  'sprintengine.help',
  'sprintengine.init',
  'sprintengine.join',
  'sprintengine.plan.add_dependency',
  'sprintengine.plan.add_task',
  'sprintengine.plan.address_reviews',
  'sprintengine.plan.delete_task',
  'sprintengine.plan.list',
  'sprintengine.plan.read',
  'sprintengine.plan.remove_dependency',
  'sprintengine.plan.review_status',
  'sprintengine.plan.start_review',
  'sprintengine.plan.update_task',
  'sprintengine.recover',
  'sprintengine.roles.get',
  'sprintengine.roles.list',
  'sprintengine.roster.add',
  'sprintengine.roster.list',
  'sprintengine.roster.replenish',
  'sprintengine.roster.retire',
  'sprintengine.run.get',
  'sprintengine.run.policy.get',
  'sprintengine.run.subscribe',
  'sprintengine.skill.get',
  'sprintengine.skills.list',
  'sprintengine.soul.get',
  'sprintengine.subscribe',
  'sprintengine.summary',
  'sprintengine.task.claim',
  'sprintengine.task.comment',
  'sprintengine.task.comment.list',
  'sprintengine.task.get',
  'sprintengine.task.list',
  'sprintengine.task.log',
  'sprintengine.task.next',
  'sprintengine.task.note',
  'sprintengine.task.publish',
  'sprintengine.task.ready',
  'sprintengine.task.release',
  'sprintengine.task.request_changes',
  'sprintengine.task.resolve_input',
  'sprintengine.task.status',
  'sprintengine.triage.needs_input',
  'sprintengine.vcs.commit',
  'sprintengine.vcs.pr',
  'sprintengine.vcs.status',
] as const

export type SprintEngineToolName = (typeof SPRINTENGINE_TOOL_NAMES)[number]
