#!/usr/bin/env python3
"""Swarm coordination tool for specialist agents.

WARNING: Do not edit swarm/state.json directly.
All updates must go through this tool.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml  # type: ignore
except ImportError as exc:
    raise SystemExit(
        "PyYAML is required. Install with: python3 -m pip install pyyaml"
    ) from exc


VALID_TASK_STATUSES = {"todo", "in_progress", "needs_input", "done"}
ACTIVE_TASK_STATUSES = {"in_progress", "needs_input"}
VALID_ROLES = {"architect", "product", "developer", "frontend", "tester", "security"}
PLAN_REVIEW_ROLES = VALID_ROLES - {"architect"}
PLAN_REVIEW_FOCUS = {
    "product": "scope fit, user value, prioritization, adoption risk, and missing requirements",
    "developer": "implementation sequence, integration risk, data flow, backend/API impact, and owned paths",
    "frontend": "interaction design, UI architecture, accessibility, responsive behavior, and user workflow",
    "tester": "test strategy, acceptance criteria, regression coverage, edge cases, and release confidence",
    "security": "trust boundaries, command safety, secrets, permissions, abuse cases, and hardening",
}

PROMPTS_DIR = Path(__file__).resolve().parent.parent / "prompts"
SPECIALIST_PROMPT_FILES = {
    "architect": "architect-prompt.md",
    "developer": "developer-prompt.md",
    "frontend": "frontend-design-promt.md",
    "tester": "qa-test-prompt.md",
    "security": "security-review-prompt.md",
}

STATE_NOTICE = (
    "DO NOT EDIT THIS FILE DIRECTLY. "
    "All updates must go through the swarm tool "
    "(swarm plan add-task, swarm task status, swarm task log, etc.). "
    "Direct edits will be overwritten and may corrupt swarm state."
)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def default_state_path(start: Optional[Path] = None) -> Path:
    import sys
    env_path = os.environ.get("SWARM_STATE_PATH")
    if env_path:
        print(f"[swarm] state path from SWARM_STATE_PATH: {env_path}", file=sys.stderr)
        return Path(env_path)
    current = (start or Path.cwd()).resolve()
    print(f"[swarm] SWARM_STATE_PATH not set, scanning from: {current}", file=sys.stderr)
    for candidate in [current, *current.parents]:
        p = candidate / "swarm" / "state.yaml"
        if p.exists():
            print(f"[swarm] found: {p}", file=sys.stderr)
            return p
        nested = sorted((candidate / "swarm").glob("*/state.yaml"))
        if len(nested) == 1:
            print(f"[swarm] found nested: {nested[0]}", file=sys.stderr)
            return nested[0]
        if len(nested) > 1:
            names = [f.parent.name for f in nested]
            print(f"[swarm] multiple teams found in {candidate}/swarm/: {names}", file=sys.stderr)
            raise SystemExit(
                f"Multiple swarm teams found: {', '.join(names)}\n"
                f"Specify which one with: --state <path>\n"
                + "\n".join(f"  {f}" for f in nested)
            )
    fallback = current / "swarm" / "state.yaml"
    print(f"[swarm] nothing found, defaulting to: {fallback}", file=sys.stderr)
    return fallback


def specialist_prompt_dir_candidates() -> List[Path]:
    script_path = Path(__file__).resolve()
    candidates = [
        Path.cwd() / "specialist-prompts",
        script_path.parents[4] / "specialist-prompts",
    ]
    return list(dict.fromkeys(candidates))


def load_specialist_prompt(role: str) -> Optional[str]:
    file_name = SPECIALIST_PROMPT_FILES.get(role)
    if not file_name:
        return None

    for prompt_dir in specialist_prompt_dir_candidates():
        path = prompt_dir / file_name
        if path.exists():
            return path.read_text(encoding="utf-8").strip()

    return None


def compose_prompt(
    base_heading: str,
    base_prompt: str,
    specialist_prompt: Optional[str],
    priority_text: str,
) -> str:
    if not specialist_prompt:
        return base_prompt

    return "\n\n".join([
        base_heading,
        base_prompt,
        "---",
        "# Specialist Operating Prompt",
        (
            "Apply this role-specific expertise while following the swarm coordination rules above. "
            "If these sections conflict, the swarm coordination rules, task card, owned paths, and "
            "current user instructions take precedence."
        ),
        specialist_prompt,
        "---",
        "# Rule Priority",
        priority_text,
    ])


def load_prompt(role: str) -> str:
    path = PROMPTS_DIR / f"{role}.md"
    if not path.exists():
        raise SystemExit(f"Prompt file not found for role {role!r}: {path}")
    swarm_prompt = path.read_text(encoding="utf-8").strip()
    return compose_prompt(
        "# Swarm Coordination Rules",
        swarm_prompt,
        load_specialist_prompt(role),
        (
            "The swarm rules remain mandatory: coordinate through the swarm tool, do not edit swarm "
            "state files directly, respect task ownership, log evidence, and stop when your swarm role "
            "instructions tell you to stop."
        ),
    )


def backup_state_file(path: Path) -> Path:
    if not path.exists():
        raise SystemExit(f"State file not found: {path}")
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup = path.with_name(f"state-{timestamp}.yaml")
    attempt = 1
    while backup.exists():
        backup = path.with_name(f"state-{timestamp}-{attempt}.yaml")
        attempt += 1
    backup.write_bytes(path.read_bytes())
    return backup


# ---------------------------------------------------------------------------
# State I/O
# ---------------------------------------------------------------------------

class StateLock:
    def __init__(self, path: Path, timeout: float = 30.0, poll: float = 0.2):
        self.path = path
        self.timeout = timeout
        self.poll = poll
        self.fd: Optional[int] = None

    def acquire(self) -> None:
        deadline = time.monotonic() + self.timeout
        payload = json.dumps({"pid": os.getpid(), "createdAt": now_iso()})
        while True:
            try:
                self.fd = os.open(str(self.path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.write(self.fd, payload.encode())
                return
            except FileExistsError:
                if time.monotonic() >= deadline:
                    raise SystemExit(f"Timed out waiting for lock: {self.path}")
                time.sleep(self.poll)

    def release(self) -> None:
        if self.fd is not None:
            os.close(self.fd)
            self.fd = None
        try:
            self.path.unlink()
        except FileNotFoundError:
            pass

    def __enter__(self) -> "StateLock":
        self.acquire()
        return self

    def __exit__(self, *_: Any) -> None:
        self.release()


def load_state(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"State file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"Unexpected state shape in {path}")
    data.pop("_notice", None)
    data.setdefault("events", [])
    data.setdefault("artifacts", [])
    data.setdefault("tasks", [])
    data.setdefault("agents", {})
    data.setdefault("roles", {})
    data.setdefault("swarm", {})
    return data


def save_state(path: Path, state: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    output = {"_notice": STATE_NOTICE, **state}
    with path.open("w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)
        f.write("\n")


def with_locked_state(path: Path, handler) -> Dict[str, Any]:
    lock = StateLock(path.with_suffix(f"{path.suffix}.lock"))
    with lock:
        state = load_state(path)
        result = handler(state)
        if result.get("write", True):
            save_state(path, state)
        result.pop("write", None)
        return result


# ---------------------------------------------------------------------------
# State helpers
# ---------------------------------------------------------------------------

def find_task(state: Dict[str, Any], task_id: str) -> Dict[str, Any]:
    for task in state.get("tasks", []):
        if task.get("id") == task_id:
            return task
    raise SystemExit(f"Task not found: {task_id}")


def find_task_by_id(state: Dict[str, Any], task_id: Any) -> Optional[Dict[str, Any]]:
    for task in state.get("tasks", []):
        if isinstance(task, dict) and task.get("id") == task_id:
            return task
    return None


def append_event(state: Dict[str, Any], event_type: str, actor: str, message: str) -> Dict[str, Any]:
    event = {
        "id": f"EVT-{len(state['events']) + 1:03d}",
        "timestamp": now_iso(),
        "type": event_type,
        "actor": actor,
        "message": message,
    }
    state["events"].append(event)
    state.setdefault("swarm", {})["updatedAt"] = now_iso()
    return event


def ensure_agent(state: Dict[str, Any], agent_id: str, role: Optional[str] = None) -> Dict[str, Any]:
    agents = state.setdefault("agents", {})
    agent = agents.setdefault(agent_id, {"role": role or "developer", "status": "idle", "currentTaskId": None})
    if role and not agent.get("role"):
        agent["role"] = role
    agent.setdefault("status", "idle")
    agent.setdefault("currentTaskId", None)
    return agent


def set_agent_idle(agent: Dict[str, Any]) -> None:
    agent["status"] = "idle"
    agent["currentTaskId"] = None


def set_agent_done(agent: Dict[str, Any]) -> None:
    agent["status"] = "done"
    agent["currentTaskId"] = None


def set_agent_active(agent: Dict[str, Any], task: Dict[str, Any]) -> None:
    agent["status"] = "needs_input" if task.get("status") == "needs_input" else "running"
    agent["currentTaskId"] = task.get("id")


def clear_task_refs(state: Dict[str, Any], task_id: str) -> List[str]:
    cleared = []
    for agent_id, agent in state.get("agents", {}).items():
        if isinstance(agent, dict) and agent.get("currentTaskId") == task_id:
            set_agent_idle(agent)
            cleared.append(str(agent_id))
    return cleared


def reconcile_agent(state: Dict[str, Any], agent_id: str, role: str) -> Dict[str, Any]:
    agent = ensure_agent(state, agent_id, role)
    agent["role"] = role
    repairs = []

    current_task_id = agent.get("currentTaskId")
    if current_task_id:
        current_task = find_task_by_id(state, current_task_id)
        if not current_task or current_task.get("status") not in ACTIVE_TASK_STATUSES:
            set_agent_idle(agent)
            repairs.append(f"cleared stale task ref {current_task_id}")
        elif current_task.get("ownerAgentId") in (None, "", agent_id):
            current_task["ownerAgentId"] = agent_id
            set_agent_active(agent, current_task)
            return {"agent": agent, "activeTask": current_task, "repairs": repairs}
        else:
            set_agent_idle(agent)
            repairs.append(f"cleared task {current_task_id} owned by {current_task.get('ownerAgentId')}")

    active_task = next(
        (t for t in state.get("tasks", [])
         if isinstance(t, dict) and t.get("ownerAgentId") == agent_id and t.get("status") in ACTIVE_TASK_STATUSES),
        None,
    )
    if active_task:
        set_agent_active(agent, active_task)
        return {"agent": agent, "activeTask": active_task, "repairs": repairs}

    if agent.get("status") == "done":
        agent["currentTaskId"] = None
        return {"agent": agent, "activeTask": None, "repairs": repairs}

    set_agent_idle(agent)
    return {"agent": agent, "activeTask": None, "repairs": repairs}


def assign_task(state: Dict[str, Any], task: Dict[str, Any], agent_id: str) -> Dict[str, Any]:
    task["ownerAgentId"] = agent_id
    task["status"] = "in_progress"
    task["startedAt"] = task.get("startedAt") or now_iso()
    agent = ensure_agent(state, agent_id, task.get("role"))
    set_agent_active(agent, task)
    return {"agent": agent}


def recompute_phase(state: Dict[str, Any]) -> None:
    swarm = state.setdefault("swarm", {})
    tasks = state.get("tasks", [])
    if tasks and all(t.get("status") == "done" for t in tasks):
        swarm["status"] = "completed"
        return
    if any(t.get("status") in ACTIVE_TASK_STATUSES for t in tasks):
        swarm["status"] = "executing"
        return
    swarm["status"] = "planned" if tasks else "planning"


def ensure_evidence(task: Dict[str, Any]) -> Dict[str, Any]:
    ev = task.setdefault("evidence", {})
    ev.setdefault("summary", "")
    ev.setdefault("touchedFiles", [])
    ev.setdefault("commandsRan", [])
    ev.setdefault("results", [])
    return ev


def task_is_ready(state: Dict[str, Any], task: Dict[str, Any]) -> bool:
    if task.get("status") != "todo" or task.get("ownerAgentId"):
        return False
    for dep_id in task.get("dependsOn", []):
        dep = next((t for t in state.get("tasks", []) if t.get("id") == dep_id), None)
        if dep is None or dep.get("status") != "done":
            return False
    return True


def normalize_task(raw: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(raw, dict):
        raise SystemExit("Each task must be an object.")
    task_id = str(raw.get("id", "")).strip()
    title = str(raw.get("title", "")).strip()
    role = str(raw.get("role", "")).strip()
    if not task_id:
        raise SystemExit("Each task must have a non-empty id.")
    if not title:
        raise SystemExit(f"Task {task_id} must have a non-empty title.")
    if role not in VALID_ROLES:
        raise SystemExit(f"Task {task_id} has invalid role {role!r}.")
    status = str(raw.get("status", "todo")).strip() or "todo"
    if status not in VALID_TASK_STATUSES:
        raise SystemExit(f"Task {task_id} has invalid status {status!r}.")
    ev = raw.get("evidence") if isinstance(raw.get("evidence"), dict) else {}
    return {
        "id": task_id,
        "title": title,
        "description": str(raw.get("description", "")).strip(),
        "role": role,
        "status": status,
        "ownerAgentId": raw.get("ownerAgentId") or None,
        "dependsOn": [str(i).strip() for i in raw.get("dependsOn", []) if str(i).strip()],
        "ownedPaths": [str(i).strip() for i in raw.get("ownedPaths", []) if str(i).strip()],
        "acceptanceCriteria": [str(i).strip() for i in raw.get("acceptanceCriteria", []) if str(i).strip()],
        "implementationNotes": [str(i).strip() for i in raw.get("implementationNotes", []) if str(i).strip()],
        "evidence": {
            "summary": str(ev.get("summary", "")).strip(),
            "touchedFiles": [str(i).strip() for i in ev.get("touchedFiles", []) if str(i).strip()],
            "commandsRan": [str(i).strip() for i in ev.get("commandsRan", []) if str(i).strip()],
            "results": [str(i).strip() for i in ev.get("results", []) if str(i).strip()],
        },
        "notes": [str(i).strip() for i in raw.get("notes", []) if str(i).strip()],
        "startedAt": raw.get("startedAt") or None,
        "completedAt": raw.get("completedAt") or None,
    }


def next_task_id(tasks: List[Dict[str, Any]]) -> str:
    used = {str(t.get("id", "")) for t in tasks if isinstance(t, dict)}
    index = 1
    while f"T{index}" in used:
        index += 1
    return f"T{index}"


def build_task_from_args(args: argparse.Namespace, state: Dict[str, Any]) -> Dict[str, Any]:
    task_id = getattr(args, "task_id", None) or next_task_id(state.get("tasks", []))
    raw = {
        "id": task_id,
        "title": args.title,
        "description": getattr(args, "description", "") or "",
        "role": args.role,
        "status": "todo",
        "ownerAgentId": None,
        "dependsOn": getattr(args, "depends_on", None) or [],
        "ownedPaths": getattr(args, "path", None) or [],
        "acceptanceCriteria": getattr(args, "acceptance", None) or [],
        "implementationNotes": getattr(args, "note", None) or [],
        "evidence": {"summary": "", "touchedFiles": [], "commandsRan": [], "results": []},
        "notes": [],
        "startedAt": None,
        "completedAt": None,
    }
    task = normalize_task(raw)
    existing_ids = {str(t.get("id")) for t in state.get("tasks", []) if isinstance(t, dict)}
    if task["id"] in existing_ids:
        raise SystemExit(f"Task id already exists: {task['id']}")
    missing = [dep for dep in task["dependsOn"] if dep not in existing_ids]
    if missing:
        raise SystemExit(f"Unknown dependency for {task['id']}: {', '.join(missing)}")
    return task


def task_ids(state: Dict[str, Any]) -> set:
    return {str(t.get("id")) for t in state.get("tasks", []) if isinstance(t, dict) and t.get("id")}


def ensure_task_can_be_replanned(task: Dict[str, Any], force: bool = False) -> None:
    if force:
        return
    if task.get("status") != "todo" or task.get("ownerAgentId"):
        raise SystemExit(
            f"Task {task.get('id')} has already started. "
            "Use --force only if you intentionally want to replan active or completed work."
        )


def set_unique_list(task: Dict[str, Any], key: str, values: Optional[List[str]]) -> None:
    if values is None:
        return
    task[key] = unique_strings(values)


def add_unique_values(task: Dict[str, Any], key: str, values: List[str]) -> List[str]:
    existing = task.setdefault(key, [])
    seen = set(existing)
    added = []
    for value in values:
        item = str(value).strip()
        if not item or item in seen:
            continue
        existing.append(item)
        seen.add(item)
        added.append(item)
    return added


def remove_values(task: Dict[str, Any], key: str, values: List[str]) -> List[str]:
    targets = {str(value).strip() for value in values if str(value).strip()}
    before = [str(value) for value in task.get(key, [])]
    task[key] = [value for value in before if value not in targets]
    return [value for value in before if value in targets]


def task_dependents(state: Dict[str, Any], task_id: str) -> List[str]:
    return [
        str(task.get("id"))
        for task in state.get("tasks", [])
        if isinstance(task, dict) and task_id in task.get("dependsOn", [])
    ]


def unique_strings(values: List[Any]) -> List[str]:
    seen: set = set()
    result = []
    for v in values:
        if not isinstance(v, str):
            continue
        s = v.strip()
        if s and s not in seen:
            seen.add(s)
            result.append(s)
    return result


def plan_path_for_state(state_path: Path) -> Path:
    return state_path.parent / "plan.md"


def plan_reviews_dir_for_state(state_path: Path) -> Path:
    return state_path.parent / "plan-reviews"


def default_swarm_name_for_state(state_path: Path) -> str:
    team_dir_name = state_path.parent.name
    return "Swarm Team" if team_dir_name == "swarm" else team_dir_name


def slugify_team_name(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    return slug or "swarm-team"


def handover_path_for_state(state_path: Path) -> Path:
    return state_path.parent / "handover.md"


def safe_review_filename(agent_id: str) -> str:
    name = re.sub(r"[^A-Za-z0-9._-]+", "-", agent_id.strip()).strip(".-")
    return f"{name or 'agent'}.md"


def plan_fingerprint(plan_path: Path) -> str:
    if not plan_path.exists():
        raise SystemExit(f"Plan file not found: {plan_path}")
    return hashlib.sha256(plan_path.read_bytes()).hexdigest()


def expected_plan_reviewers(state: Dict[str, Any]) -> List[Dict[str, str]]:
    reviewers = []
    for agent_id, agent in state.get("agents", {}).items():
        if not isinstance(agent, dict):
            continue
        role = str(agent.get("role", "")).strip()
        if role not in PLAN_REVIEW_ROLES:
            continue
        reviewers.append({"id": str(agent_id), "role": role})
    return sorted(reviewers, key=lambda item: (item["role"], item["id"]))


def parse_review_metadata(path: Path) -> Dict[str, Any]:
    try:
        content = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        content = path.read_text(encoding="utf-8", errors="replace")
    fingerprint_match = re.search(r"(?im)^Plan fingerprint:\s*([A-Fa-f0-9]{64})\s*$", content)
    verdict_match = re.search(r"(?im)^Verdict:\s*([^\n]+)\s*$", content)
    role_match = re.search(r"(?im)^Role:\s*([A-Za-z0-9_-]+)\s*$", content)
    agent_match = re.search(r"(?im)^Agent:\s*([A-Za-z0-9._-]+)\s*$", content)
    return {
        "path": str(path),
        "filename": path.name,
        "agentId": agent_match.group(1).strip() if agent_match else path.stem,
        "role": role_match.group(1).strip() if role_match else None,
        "planFingerprint": fingerprint_match.group(1).lower() if fingerprint_match else None,
        "verdict": verdict_match.group(1).strip() if verdict_match else "unknown",
        "content": content,
    }


def build_plan_review_status(state: Dict[str, Any], state_path: Path) -> Dict[str, Any]:
    plan_path = plan_path_for_state(state_path)
    reviews_dir = plan_reviews_dir_for_state(state_path)
    current_fingerprint = plan_fingerprint(plan_path)
    expected = expected_plan_reviewers(state)
    expected_by_id = {reviewer["id"]: reviewer for reviewer in expected}
    files = sorted(reviews_dir.glob("*.md")) if reviews_dir.exists() else []
    reviews = []

    for path in files:
        metadata = parse_review_metadata(path)
        metadata["stale"] = metadata.get("planFingerprint") != current_fingerprint
        metadata["expected"] = metadata.get("agentId") in expected_by_id
        metadata.pop("content", None)
        reviews.append(metadata)

    review_ids = {review.get("agentId") for review in reviews}
    missing = [reviewer for reviewer in expected if reviewer["id"] not in review_ids]
    stale = [review for review in reviews if review.get("stale")]
    unexpected = [review for review in reviews if not review.get("expected")]
    completed = [
        review for review in reviews
        if not review.get("stale") and str(review.get("verdict", "")).lower() in {"approve", "needs_changes", "blocked"}
    ]

    return {
        "planPath": str(plan_path),
        "reviewsDirectory": str(reviews_dir),
        "planFingerprint": current_fingerprint,
        "expectedReviewers": expected,
        "reviews": reviews,
        "missingReviewers": missing,
        "staleReviews": stale,
        "unexpectedReviews": unexpected,
        "counts": {
            "expected": len(expected),
            "completed": len(completed),
            "missing": len(missing),
            "stale": len(stale),
            "unexpected": len(unexpected),
        },
    }


def build_plan_review_template(agent_id: str, role: str, plan_path: Path, fingerprint: str) -> str:
    role_label = role.replace("-", " ").title()
    return "\n".join([
        f"# Plan Review: {role_label}",
        "",
        f"Agent: {agent_id}",
        f"Role: {role}",
        f"Plan: {plan_path.name}",
        f"Plan fingerprint: {fingerprint}",
        "Verdict: pending",
        "",
        "## Summary",
        "",
        "## Blocking Issues",
        "",
        "## Recommended Changes",
        "",
        "## Task Graph Feedback",
        "",
        "## Missing Acceptance Criteria",
        "",
        "## Risks",
        "",
        "## Questions For Architect",
        "",
    ])


def build_plan_review_prompt(
    agent_id: str,
    role: str,
    plan_path: Path,
    review_path: Path,
    fingerprint: str,
    existing_review: bool,
) -> str:
    action = "Replace your existing review" if existing_review else "Write your review"
    review_prompt = "\n".join([
        f"You are the {role} specialist reviewing the architect's swarm plan.",
        "",
        "Do not claim tasks, do not implement, and do not edit state.yaml.",
        "",
        f"Plan file: {plan_path}",
        f"Your review file: {review_path}",
        f"Current plan fingerprint: {fingerprint}",
        f"Review focus: {PLAN_REVIEW_FOCUS.get(role, 'specialist risks, gaps, and execution quality')}.",
        "",
        "Steps:",
        "1. Read the full architect plan.",
        "2. Inspect the repository only as needed to validate the plan from your specialty.",
        "3. Evaluate whether the task graph, owned paths, dependencies, and acceptance criteria are sufficient.",
        f"4. {action} at the exact review file path above.",
        "5. Set `Verdict:` to one of: approve, needs_changes, blocked.",
        "6. Keep feedback concrete and actionable for the architect.",
        "",
        "Required markdown sections:",
        "- Summary",
        "- Blocking Issues",
        "- Recommended Changes",
        "- Task Graph Feedback",
        "- Missing Acceptance Criteria",
        "- Risks",
        "- Questions For Architect",
        "",
        "Do not update the task board. The architect will address feedback with `swarm plan address-reviews`.",
    ])
    return compose_prompt(
        "# Swarm Plan Review Rules",
        review_prompt,
        load_specialist_prompt(role),
        (
            "The plan review rules remain mandatory: do not claim tasks, do not implement, do not edit "
            "state files, write only the assigned review file, and keep feedback concrete for the architect."
        ),
    )


def build_address_reviews_prompt(
    state: Dict[str, Any],
    state_path: Path,
    status: Dict[str, Any],
    review_contents: List[Dict[str, str]],
) -> str:
    plan_path = plan_path_for_state(state_path)
    plan_content = plan_path.read_text(encoding="utf-8")
    review_blocks = []

    for review in review_contents:
        review_blocks.extend([
            f"## Review File: {review['path']}",
            "",
            review["content"].rstrip(),
            "",
        ])

    warnings = []
    if status["missingReviewers"]:
        missing = ", ".join(f"{r['id']} ({r['role']})" for r in status["missingReviewers"])
        warnings.append(f"- Missing expected reviews: {missing}")
    if status["staleReviews"]:
        stale = ", ".join(str(r["path"]) for r in status["staleReviews"])
        warnings.append(f"- Stale reviews whose fingerprint does not match the current plan: {stale}")
    if status["unexpectedReviews"]:
        unexpected = ", ".join(str(r["path"]) for r in status["unexpectedReviews"])
        warnings.append(f"- Unexpected review files: {unexpected}")
    warning_block = "\n".join(warnings) if warnings else "- No missing, stale, or unexpected review files detected."

    return "\n".join([
        "You are the swarm architect addressing specialist plan reviews.",
        "",
        "Do not implement. Do not hand-edit state.yaml. Your job is to revise the plan and task graph.",
        "",
        f"Plan file: {plan_path}",
        f"Plan fingerprint: {status['planFingerprint']}",
        "",
        "Review status:",
        warning_block,
        "",
        "Steps:",
        "1. Read the current plan and all specialist review feedback below.",
        "2. Decide which feedback to accept, adapt, or reject.",
        "3. Update plan.md directly when the human-readable plan needs changes.",
        "4. Update the task graph only with swarm plan commands:",
        "   - swarm plan update-task",
        "   - swarm plan add-task",
        "   - swarm plan delete-task",
        "   - swarm plan add-dependency",
        "   - swarm plan remove-dependency",
        "5. Do not start implementation work.",
        "6. When done, tell the user which review items were accepted, adapted, or rejected.",
        "",
        "# Current Plan",
        "",
        plan_content.rstrip(),
        "",
        "# Specialist Reviews",
        "",
        "\n".join(review_blocks).rstrip() or "(No plan review files found.)",
    ])


def build_run_summary(state: Dict[str, Any]) -> Dict[str, Any]:
    tasks = state.get("tasks", [])
    completed = [t for t in tasks if t.get("status") == "done"]
    touched_files: List[Any] = []
    commands_ran: List[Any] = []
    results: List[str] = []
    task_summaries = []
    open_questions: List[str] = []

    for t in completed:
        ev = ensure_evidence(t)
        task_summaries.append({
            "id": t.get("id"),
            "title": t.get("title"),
            "summary": ev.get("summary") or "No summary recorded.",
            "ownerAgentId": t.get("ownerAgentId"),
            "completedAt": t.get("completedAt"),
        })
        touched_files.extend(ev.get("touchedFiles", []))
        commands_ran.extend(ev.get("commandsRan", []))
        results.extend(f"{t.get('id')}: {r}" for r in ev.get("results", []) if isinstance(r, str))

    for t in tasks:
        for q in t.get("notes", []):
            if isinstance(q, str) and q.strip():
                open_questions.append(f"{t.get('id')}: {q.strip()}")

    swarm = state.get("swarm", {})
    return {
        "goal": swarm.get("goal", ""),
        "status": swarm.get("status", "planning"),
        "tasks": {"total": len(tasks), "completed": len(completed), "remaining": max(0, len(tasks) - len(completed))},
        "touchedFiles": unique_strings(touched_files),
        "commandsRan": unique_strings(commands_ran),
        "results": results,
        "completedTasks": task_summaries,
        "openQuestions": open_questions,
    }


# ---------------------------------------------------------------------------
# Command handlers
# ---------------------------------------------------------------------------

def cmd_handover(args: argparse.Namespace) -> Dict[str, Any]:
    team_slug = slugify_team_name(args.name)
    state_path = (args.state or (Path.cwd() / "swarm" / team_slug / "state.yaml")).resolve()
    team_dir = state_path.parent
    handover_path = handover_path_for_state(state_path)

    existing = [path for path in [state_path, handover_path] if path.exists()]
    if existing and not args.force:
        return {
            "ok": False,
            "error": "Team already has bootstrap files. Use --force only if you intend to replace the state/handover bootstrap.",
            "existing": [str(path) for path in existing],
            "write": False,
        }

    handover_text = ""
    if args.handover:
        handover_text = args.handover.read_text(encoding="utf-8")
    elif getattr(args, "handover_stdin", False):
        handover_text = sys.stdin.read()
    elif args.handover_text:
        handover_text = args.handover_text

    team_dir.mkdir(parents=True, exist_ok=True)
    initial: Dict[str, Any] = {
        "swarm": {"name": team_slug, "goal": args.goal or "", "status": "planning"},
        "tasks": [],
        "agents": {},
        "events": [
            {
                "id": "EVT-001",
                "timestamp": now_iso(),
                "type": "handover_created",
                "actor": args.actor,
                "message": f"{args.actor} created swarm handover for team {team_slug}.",
            }
        ],
        "artifacts": [],
        "roles": {},
    }
    save_state(state_path, initial)

    wrote_handover = False
    if handover_text.strip():
        handover_path.write_text(handover_text.rstrip() + "\n", encoding="utf-8")
        wrote_handover = True

    init_command = f"swarm --state {json.dumps(str(state_path))} init"
    architect_startup_prompt = "\n\n".join([
        f"Use the existing swarm team `{team_slug}`.",
        "Fetch the canonical architect instructions from the Python tool.",
        "Run:",
        f"```bash\n{init_command}\n```",
        "Then follow the returned prompt. If `handover.md` exists, treat it as incoming context, not as the final plan.",
    ])

    return {
        "ok": True,
        "action": "handover",
        "team": team_slug,
        "statePath": str(state_path),
        "handoverPath": str(handover_path) if wrote_handover else None,
        "planPath": str(plan_path_for_state(state_path)),
        "architectStartupPrompt": architect_startup_prompt,
    }


def cmd_init(args: argparse.Namespace) -> Dict[str, Any]:
    state_path = args.state
    default_name = default_swarm_name_for_state(state_path)
    if not state_path.exists():
        state_path.parent.mkdir(parents=True, exist_ok=True)
        initial: Dict[str, Any] = {
            "swarm": {"name": default_name, "goal": getattr(args, "goal", "") or "", "status": "planning"},
            "tasks": [],
            "agents": {},
            "events": [],
            "artifacts": [],
            "roles": {},
        }
        save_state(state_path, initial)

    state = load_state(state_path)
    swarm = state.setdefault("swarm", {})
    if not swarm.get("name"):
        swarm["name"] = default_name
        save_state(state_path, state)
    plan_path = state_path.parent / "plan.md"
    handover_path = handover_path_for_state(state_path)
    handover_exists = handover_path.exists()
    plan_exists = plan_path.exists()
    goal = swarm.get("goal") or "(not set — read the codebase for context)"
    prompt = load_prompt("architect")
    existing_plan_step = "Review and update the existing plan" if plan_exists else "Write a compact plan"
    handover_step = (
        f"1. Read `{handover_path}` as incoming handoff context, not final truth\n"
        "2. Read the codebase and validate the handoff against the repository and current user instructions\n"
    ) if handover_exists else (
        "1. Read the codebase and understand what needs to be done\n"
    )
    next_step_number = 3 if handover_exists else 2
    directive = (
        "\n\n---\n"
        "## Your Goal\n"
        f"{goal}\n\n"
        "## Steps\n"
        f"{handover_step}"
        f"{next_step_number}. {existing_plan_step} at `{plan_path}` as the architect-owned final execution plan\n"
        f"{next_step_number + 1}. Build the task board one task at a time with `swarm plan add-task`\n"
        f"{next_step_number + 2}. During review, revise tasks with `swarm plan update-task`, `swarm plan delete-task`, `swarm plan add-dependency`, and `swarm plan remove-dependency`\n"
        f"{next_step_number + 3}. Tell the user to review the plan and spawn the specialists they want to run\n\n"
        "**IMPORTANT: Do not edit swarm/state.json directly. "
        "All updates must go through the swarm tool.**"
    )
    return {"ok": True, "role": "architect", "action": "plan", "prompt": prompt + directive}


def cmd_join(args: argparse.Namespace) -> Dict[str, Any]:
    import sys
    print(f"[swarm] reading state from: {args.state}", file=sys.stderr)

    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        runtime = reconcile_agent(state, args.id, args.role)
        agent = runtime["agent"]
        active = runtime["activeTask"]
        ready = [t for t in state.get("tasks", []) if t.get("role") == args.role and task_is_ready(state, t)]

        if not active and agent.get("status") == "done":
            return {"ok": True, "role": args.role, "agentId": args.id, "action": "stop", "message": f"Agent '{args.id}' has already completed one task for this swarm run. Stop now; spawn a fresh {args.role} agent for additional work."}

        if not active and not ready:
            return {"ok": True, "role": args.role, "agentId": args.id, "action": "stop", "message": f"No tasks are currently ready for the '{args.role}' role. Either all tasks are complete or dependencies are not yet resolved. Stop now."}

        prompt = load_prompt(args.role)
        if active:
            task_id = active.get("id")
            task_title = active.get("title") or "(untitled task)"
            directive = (
                f"\n\n---\n"
                f"## Your First Action\n"
                f"You are agent `{args.id}` with role `{args.role}`.\n"
                f"You already have active task `{task_id}`: {task_title}.\n\n"
                f"Run:\n```\nswarm task next --role {args.role} --id {args.id}\n```\n\n"
                f"This reconnects you to your existing active task instead of claiming a new one. "
                f"Continue the task, log evidence, mark it done, then stop. "
                f"Do not claim another task with this agent after marking the task done.\n\n"
                "**IMPORTANT: Do not edit swarm/state.json directly. "
                "All updates must go through the swarm tool.**"
            )
            return {"ok": True, "role": args.role, "agentId": args.id, "action": "resume", "task": active, "prompt": prompt + directive}

        directive = (
            f"\n\n---\n"
            f"## Your First Action\n"
            f"You are agent `{args.id}` with role `{args.role}`.\n"
            f"There are **{len(ready)} task(s)** ready for your role.\n\n"
            f"Run:\n```\nswarm task next --role {args.role} --id {args.id}\n```\n\n"
            f"Complete exactly one task, log evidence, mark it done, then stop. "
            f"Do not claim another task with this agent after marking the task done.\n\n"
            "**IMPORTANT: Do not edit swarm/state.json directly. "
            "All updates must go through the swarm tool.**"
        )
        return {"ok": True, "role": args.role, "agentId": args.id, "action": "work", "readyTaskCount": len(ready), "prompt": prompt + directive}

    return with_locked_state(args.state, run)


def build_recovery_prompt(state: Dict[str, Any], state_path: Path, backup_path: Path) -> str:
    swarm = state.get("swarm", {})
    goal = swarm.get("goal") or "(not set - read the codebase for context)"
    tasks = state.get("tasks", [])
    task_count = len(tasks)
    return "\n".join([
        "You are the recovery architect for this swarm.",
        f"Goal: {goal}",
        f"State file: {state_path}",
        f"Backup created: {backup_path}",
        f"Existing task count: {task_count}",
        "",
        "Keep this deliberately simple. This is an audit-only recovery pass, not a planning pass.",
        "Your only job is to compare the existing tasks against the current codebase and update each existing task status/evidence through the swarm tool.",
        "",
        "Hard rules:",
        "- Do NOT run `swarm init`.",
        "- Do NOT rewrite, replace, delete, or add tasks.",
        "- Do NOT run `swarm plan delete-task`, `swarm plan add-task`, `swarm plan update-task`, `swarm plan add-dependency`, `swarm plan remove-dependency`, or any task-board replanning command.",
        "- Do NOT edit plan.md or create a new plan.",
        "- Do NOT clear the board because tasks look stale.",
        "- Preserve task IDs, titles, descriptions, paths, dependencies, and acceptance criteria.",
        "- Only change status, notes, and evidence for tasks that already exist in state.yaml.",
        "",
        "Work through every existing task in state.yaml in order.",
        "",
        "For each task:",
        "1. Read the task title, description, owned paths, acceptance criteria, notes, and existing evidence.",
        "2. Inspect the current codebase for the relevant implementation.",
        "3. Decide the real status: todo, in_progress, needs_input, or done.",
        "4. Update only that task's status.",
        "5. If marking done or in_progress, append evidence with files checked, commands run, and a short result.",
        "6. If uncertain, mark needs_input or add a note. Do not guess.",
        "",
        "Use command discovery before your first mutation:",
        "- `swarm --help`",
        "- `swarm task status --help`",
        "- `swarm task log --help`",
        "- `swarm task note --help`",
        "",
        "Allowed write commands are limited to:",
        "- `swarm task status`",
        "- `swarm task log`",
        "- `swarm task note`",
        "",
        "If a needed command is unavailable or fails, stop and explain the blocker instead of changing the plan shape.",
    ])


def cmd_recover(args: argparse.Namespace) -> Dict[str, Any]:
    backup_path = backup_state_file(args.state)
    state = load_state(args.state)
    prompt = build_recovery_prompt(state, args.state, backup_path)
    return {
        "ok": True,
        "role": "architect",
        "action": "recover",
        "backupPath": str(backup_path),
        "taskCount": len(state.get("tasks", [])),
        "prompt": prompt,
    }


def cmd_task_list(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        ready = []
        for t in state.get("tasks", []):
            if getattr(args, "role", None) and t.get("role") != args.role:
                continue
            if task_is_ready(state, t):
                ready.append({"id": t.get("id"), "title": t.get("title"), "role": t.get("role"), "dependsOn": t.get("dependsOn", [])})
        return {"ok": True, "readyTasks": ready, "write": False}
    return with_locked_state(args.state, run)


def cmd_task_next(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        runtime = reconcile_agent(state, args.id, args.role)
        agent = runtime["agent"]
        active = runtime["activeTask"]
        if active:
            return {"ok": True, "claimed": False, "reason": "agent_already_has_active_task", "task": active, "agent": agent}
        if agent.get("status") == "done":
            return {"ok": True, "claimed": False, "reason": "agent_completed_single_task", "message": f"Agent '{args.id}' has already completed one task. Stop now; spawn a fresh {args.role} agent for additional work.", "agent": agent}

        for t in state.get("tasks", []):
            if t.get("role") != args.role or not task_is_ready(state, t):
                continue
            result = assign_task(state, t, args.id)
            recompute_phase(state)
            event = append_event(state, "task_claimed", args.id, f"{args.id} claimed {t.get('id')}.")
            return {"ok": True, "claimed": True, "task": t, "agent": result["agent"], "event": event}

        recompute_phase(state)
        return {"ok": True, "claimed": False, "reason": "no_ready_task", "message": f"No ready {args.role} tasks. Stop."}

    return with_locked_state(args.state, run)


def cmd_task_claim(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        agent = ensure_agent(state, args.id, task.get("role"))
        if agent.get("status") == "done":
            return {"ok": False, "error": f"Agent '{args.id}' has already completed one task. Spawn a fresh agent for additional work.", "agent": agent, "write": False}
        if not task_is_ready(state, task):
            return {"ok": False, "error": "Task is not ready.", "task": {"id": task.get("id"), "status": task.get("status")}, "write": False}
        result = assign_task(state, task, args.id)
        recompute_phase(state)
        event = append_event(state, "task_claimed", args.id, f"{args.id} claimed {args.task_id}.")
        return {"ok": True, "task": task, "agent": result["agent"], "event": event}
    return with_locked_state(args.state, run)


def cmd_task_status(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        actor = args.id or task.get("ownerAgentId") or task.get("role") or "agent"
        task["status"] = args.status
        if args.status == "in_progress" and not task.get("startedAt"):
            task["startedAt"] = now_iso()
        if args.status == "done":
            task["completedAt"] = now_iso()
        if getattr(args, "summary", None):
            ensure_evidence(task)["summary"] = args.summary
        if task.get("ownerAgentId"):
            agent = ensure_agent(state, task["ownerAgentId"], task.get("role"))
            if args.status == "in_progress":
                agent["status"] = "running"
                agent["currentTaskId"] = args.task_id
            elif args.status == "needs_input":
                agent["status"] = "needs_input"
                agent["currentTaskId"] = args.task_id
        cleared = []
        if args.status not in ACTIVE_TASK_STATUSES:
            cleared = clear_task_refs(state, args.task_id)
        if args.status == "done" and task.get("ownerAgentId"):
            set_agent_done(ensure_agent(state, task["ownerAgentId"], task.get("role")))
        recompute_phase(state)
        event = append_event(state, "task_status_changed", actor, f"{actor} moved {args.task_id} to {args.status}.")
        return {"ok": True, "task": task, "event": event, "clearedAgents": cleared}
    return with_locked_state(args.state, run)


def cmd_task_log(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        ev = ensure_evidence(task)
        if getattr(args, "summary", None):
            ev["summary"] = args.summary
        ev["touchedFiles"].extend(args.file or [])
        ev["commandsRan"].extend(args.command or [])
        ev["results"].extend(args.result or [])
        event = append_event(state, "task_evidence_appended", args.id, f"{args.id} logged evidence for {args.task_id}.")
        return {"ok": True, "task": task, "event": event}
    return with_locked_state(args.state, run)


def cmd_task_note(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        task.setdefault("notes", []).append(args.note)
        event = append_event(state, "task_note_added", args.id, f"{args.id} added note to {args.task_id}.")
        return {"ok": True, "task": task, "event": event}
    return with_locked_state(args.state, run)


def cmd_plan_add_task(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = build_task_from_args(args, state)
        state.setdefault("tasks", []).append(task)
        recompute_phase(state)
        event = append_event(state, "task_added", args.actor, f"{args.actor} added {task['id']}: {task['title']}.")
        return {"ok": True, "task": task, "event": event}

    return with_locked_state(args.state, run)


def cmd_plan_update_task(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        ensure_task_can_be_replanned(task, args.force)

        if args.title is not None:
            title = args.title.strip()
            if not title:
                raise SystemExit("Task title cannot be empty.")
            task["title"] = title
        if args.description is not None:
            task["description"] = args.description.strip()
        if args.clear_description:
            task["description"] = ""
        if args.role is not None:
            task["role"] = args.role

        if args.clear_paths:
            task["ownedPaths"] = []
        set_unique_list(task, "ownedPaths", args.path)

        if args.clear_acceptance:
            task["acceptanceCriteria"] = []
        set_unique_list(task, "acceptanceCriteria", args.acceptance)

        if args.clear_notes:
            task["implementationNotes"] = []
        set_unique_list(task, "implementationNotes", args.note)

        recompute_phase(state)
        event = append_event(state, "task_updated", args.actor, f"{args.actor} updated {args.task_id}.")
        return {"ok": True, "task": task, "event": event}

    return with_locked_state(args.state, run)


def cmd_plan_delete_task(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        ensure_task_can_be_replanned(task, args.force)

        dependents = task_dependents(state, args.task_id)
        if dependents and not args.unlink_dependents:
            return {
                "ok": False,
                "error": f"Task {args.task_id} is still a dependency of: {', '.join(dependents)}. Use --unlink-dependents to remove those links.",
                "write": False,
            }
        if args.unlink_dependents:
            for candidate in state.get("tasks", []):
                if isinstance(candidate, dict):
                    candidate["dependsOn"] = [dep for dep in candidate.get("dependsOn", []) if dep != args.task_id]

        clear_task_refs(state, args.task_id)
        state["tasks"] = [
            candidate for candidate in state.get("tasks", [])
            if not (isinstance(candidate, dict) and candidate.get("id") == args.task_id)
        ]
        recompute_phase(state)
        event = append_event(state, "task_deleted", args.actor, f"{args.actor} deleted {args.task_id}.")
        return {"ok": True, "deletedTaskId": args.task_id, "unlinkedDependents": dependents if args.unlink_dependents else [], "event": event}

    return with_locked_state(args.state, run)


def cmd_plan_add_dependency(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        ensure_task_can_be_replanned(task, args.force)
        ids = task_ids(state)
        deps = args.depends_on or []
        missing = [dep for dep in deps if dep not in ids]
        if missing:
            raise SystemExit(f"Unknown dependency for {args.task_id}: {', '.join(missing)}")
        if args.task_id in deps:
            raise SystemExit("A task cannot depend on itself.")

        added = add_unique_values(task, "dependsOn", deps)
        recompute_phase(state)
        event = append_event(state, "task_dependencies_added", args.actor, f"{args.actor} added dependencies to {args.task_id}: {', '.join(added) or 'none'}.")
        return {"ok": True, "task": task, "added": added, "event": event}

    return with_locked_state(args.state, run)


def cmd_plan_remove_dependency(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        ensure_task_can_be_replanned(task, args.force)
        removed = remove_values(task, "dependsOn", args.depends_on or [])
        recompute_phase(state)
        event = append_event(state, "task_dependencies_removed", args.actor, f"{args.actor} removed dependencies from {args.task_id}: {', '.join(removed) or 'none'}.")
        return {"ok": True, "task": task, "removed": removed, "event": event}

    return with_locked_state(args.state, run)


def cmd_plan_list(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        tasks = state.get("tasks", [])
        rows = [
            {
                "id": t.get("id"),
                "title": t.get("title"),
                "role": t.get("role"),
                "status": t.get("status"),
                "dependsOn": t.get("dependsOn", []),
            }
            for t in tasks
            if isinstance(t, dict)
        ]
        return {"ok": True, "tasks": rows, "write": False}

    return with_locked_state(args.state, run)


def cmd_plan_start_review(args: argparse.Namespace) -> Dict[str, Any]:
    state = load_state(args.state)
    plan_path = plan_path_for_state(args.state)
    reviews_dir = plan_reviews_dir_for_state(args.state)
    fingerprint = plan_fingerprint(plan_path)
    reviews_dir.mkdir(parents=True, exist_ok=True)

    review_path = reviews_dir / safe_review_filename(args.id)
    existing_review = review_path.exists()
    if not existing_review:
        review_path.write_text(
            build_plan_review_template(args.id, args.role, plan_path, fingerprint),
            encoding="utf-8",
        )

    prompt = build_plan_review_prompt(
        args.id,
        args.role,
        plan_path,
        review_path,
        fingerprint,
        existing_review,
    )
    known_reviewers = expected_plan_reviewers(state)
    return {
        "ok": True,
        "role": args.role,
        "agentId": args.id,
        "action": "plan_review",
        "planPath": str(plan_path),
        "reviewPath": str(review_path),
        "reviewExisted": existing_review,
        "planFingerprint": fingerprint,
        "knownReviewers": known_reviewers,
        "prompt": prompt,
    }


def cmd_plan_review_status(args: argparse.Namespace) -> Dict[str, Any]:
    state = load_state(args.state)
    return {"ok": True, "action": "plan_review_status", **build_plan_review_status(state, args.state)}


def cmd_plan_address_reviews(args: argparse.Namespace) -> Dict[str, Any]:
    state = load_state(args.state)
    reviews_dir = plan_reviews_dir_for_state(args.state)
    status = build_plan_review_status(state, args.state)
    review_contents = []

    if reviews_dir.exists():
        for path in sorted(reviews_dir.glob("*.md")):
            metadata = parse_review_metadata(path)
            review_contents.append({"path": str(path), "content": metadata["content"]})

    prompt = build_address_reviews_prompt(state, args.state, status, review_contents)
    return {
        "ok": True,
        "role": "architect",
        "actor": args.actor,
        "action": "address_plan_reviews",
        "planPath": status["planPath"],
        "reviewsDirectory": status["reviewsDirectory"],
        "reviewCount": len(review_contents),
        "status": status,
        "prompt": prompt,
    }


def cmd_summary(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        return {"ok": True, "summary": build_run_summary(state), "write": False}
    return with_locked_state(args.state, run)


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

TOP_LEVEL_HELP = """\
Swarm tool — all state mutations go through here. Never edit state.json directly.

Entry points (return full system prompt for the agent):
  swarm handover --name my-team --goal "..." --handover handover.md
  swarm init [--goal "..."]
  swarm recover
  swarm join --role developer --id developer-1

Task commands:
  swarm task next   --role developer --id developer-1
  swarm task claim  --task-id T3 --id developer-1
  swarm task status --task-id T3 --status done --id developer-1
  swarm task log    --task-id T3 --id developer-1 --summary "..." --file src/foo.ts --command "npm test" --result "Passed"
  swarm task note   --task-id T3 --id developer-1 --note "Blocked on X"
  swarm task list   --role developer

Plan commands (architect only):
  swarm plan add-task --title "..." --role developer --path src/foo --acceptance "..."
  swarm plan update-task --task-id T1 --title "..." --path src/foo --acceptance "..."
  swarm plan add-dependency --task-id T2 --depends-on T1
  swarm plan remove-dependency --task-id T2 --depends-on T1
  swarm plan delete-task --task-id T3 --unlink-dependents
  swarm plan start-review --role frontend --id frontend
  swarm plan review-status
  swarm plan address-reviews --actor architect
  swarm plan list

Run summary:
  swarm summary
"""


def add_handover_parser(sub: argparse._SubParsersAction, name: str, help_text: str) -> None:
    p = sub.add_parser(name, help=help_text)
    p.add_argument("--name", required=True, help="Team name; converted to a stable folder slug.")
    p.add_argument("--goal", default="", help="Goal for the future architect/swarm run.")
    handover = p.add_mutually_exclusive_group()
    handover.add_argument("--handover", type=Path, help="Path to markdown handover context to copy into handover.md.")
    handover.add_argument("--handover-text", help="Inline handover context to write to handover.md.")
    handover.add_argument("--handover-stdin", action="store_true", help="Read markdown handover context from stdin.")
    p.add_argument("--actor", default="handoff", help="Actor name for the team creation event.")
    p.add_argument("--force", action="store_true", help="Replace existing state/handover bootstrap files.")
    p.set_defaults(handler=cmd_handover, uses_state=False)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Swarm coordination tool",
        epilog=TOP_LEVEL_HELP,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--state",
        type=Path,
        default=None,
        help="Path to state file (auto-detected from cwd).",
    )

    sub = parser.add_subparsers(dest="group", required=True)

    # handover
    add_handover_parser(sub, "handover", "Create a swarm team bootstrap and canonical handover.md.")

    # init
    p = sub.add_parser("init", help="Start swarm as architect, returns full prompt.")
    p.add_argument("--goal", help="Goal for the swarm (stored in state).")
    p.set_defaults(handler=cmd_init)

    # recover
    p = sub.add_parser("recover", help="Start audit-only recovery mode, backs up state and returns full prompt.")
    p.set_defaults(handler=cmd_recover)

    # join
    p = sub.add_parser("join", help="Join swarm as worker, returns full role prompt.")
    p.add_argument("--role", required=True, choices=sorted(VALID_ROLES))
    p.add_argument("--id", required=True, help="Stable agent id, e.g. developer-1.")
    p.set_defaults(handler=cmd_join)

    # task
    task_p = sub.add_parser("task", help="Task operations.")
    task_sub = task_p.add_subparsers(dest="action", required=True)

    p = task_sub.add_parser("next", help="Claim the next ready task for your role.")
    p.add_argument("--role", required=True, choices=sorted(VALID_ROLES))
    p.add_argument("--id", required=True)
    p.set_defaults(handler=cmd_task_next)

    p = task_sub.add_parser("claim", help="Claim a specific task by ID.")
    p.add_argument("--task-id", required=True)
    p.add_argument("--id", required=True, help="Agent id.")
    p.set_defaults(handler=cmd_task_claim)

    p = task_sub.add_parser("status", help="Update task status.")
    p.add_argument("--task-id", required=True)
    p.add_argument("--status", required=True, choices=sorted(VALID_TASK_STATUSES))
    p.add_argument("--id", help="Agent id.")
    p.add_argument("--summary", help="Completion summary (used when status=done).")
    p.set_defaults(handler=cmd_task_status)

    p = task_sub.add_parser("log", help="Log work evidence (files, commands, results).")
    p.add_argument("--task-id", required=True)
    p.add_argument("--id", required=True, help="Agent id.")
    p.add_argument("--summary")
    p.add_argument("--file", action="append", metavar="PATH")
    p.add_argument("--command", action="append", metavar="CMD")
    p.add_argument("--result", action="append", metavar="RESULT")
    p.set_defaults(handler=cmd_task_log)

    p = task_sub.add_parser("note", help="Add a freeform note to a task.")
    p.add_argument("--task-id", required=True)
    p.add_argument("--id", required=True, help="Agent id.")
    p.add_argument("--note", required=True)
    p.set_defaults(handler=cmd_task_note)

    p = task_sub.add_parser("list", help="List ready tasks for a role.")
    p.add_argument("--role", choices=sorted(VALID_ROLES))
    p.set_defaults(handler=cmd_task_list)

    # plan
    plan_p = sub.add_parser("plan", help="Plan operations (architect only).")
    plan_sub = plan_p.add_subparsers(dest="action", required=True)

    p = plan_sub.add_parser("add-task", help="Append a planned task to the board.")
    p.add_argument("--actor", default="architect")
    p.add_argument("--task-id")
    p.add_argument("--title", required=True)
    p.add_argument("--description", default="")
    p.add_argument("--role", required=True, choices=sorted(VALID_ROLES))
    p.add_argument("--depends-on", action="append", default=[])
    p.add_argument("--path", action="append", default=[], help="Owned path or directory.")
    p.add_argument("--acceptance", action="append", default=[], help="Acceptance criterion.")
    p.add_argument("--note", action="append", default=[], help="Implementation note.")
    p.set_defaults(handler=cmd_plan_add_task)

    p = plan_sub.add_parser("update-task", help="Edit an existing planned task.")
    p.add_argument("--actor", default="architect")
    p.add_argument("--task-id", required=True)
    p.add_argument("--title")
    p.add_argument("--description")
    p.add_argument("--clear-description", action="store_true")
    p.add_argument("--role", choices=sorted(VALID_ROLES))
    p.add_argument("--path", action="append", help="Replace owned paths with this repeatable list.")
    p.add_argument("--clear-paths", action="store_true")
    p.add_argument("--acceptance", action="append", help="Replace acceptance criteria with this repeatable list.")
    p.add_argument("--clear-acceptance", action="store_true")
    p.add_argument("--note", action="append", help="Replace implementation notes with this repeatable list.")
    p.add_argument("--clear-notes", action="store_true")
    p.add_argument("--force", action="store_true", help="Allow editing an active or completed task.")
    p.set_defaults(handler=cmd_plan_update_task)

    p = plan_sub.add_parser("delete-task", help="Delete a planned task.")
    p.add_argument("--actor", default="architect")
    p.add_argument("--task-id", required=True)
    p.add_argument("--unlink-dependents", action="store_true", help="Remove this task from dependent tasks before deleting it.")
    p.add_argument("--force", action="store_true", help="Allow deleting an active or completed task.")
    p.set_defaults(handler=cmd_plan_delete_task)

    p = plan_sub.add_parser("add-dependency", help="Add dependency links to a task.")
    p.add_argument("--actor", default="architect")
    p.add_argument("--task-id", required=True)
    p.add_argument("--depends-on", action="append", required=True)
    p.add_argument("--force", action="store_true", help="Allow editing an active or completed task.")
    p.set_defaults(handler=cmd_plan_add_dependency)

    p = plan_sub.add_parser("remove-dependency", help="Remove dependency links from a task.")
    p.add_argument("--actor", default="architect")
    p.add_argument("--task-id", required=True)
    p.add_argument("--depends-on", action="append", required=True)
    p.add_argument("--force", action="store_true", help="Allow editing an active or completed task.")
    p.set_defaults(handler=cmd_plan_remove_dependency)

    p = plan_sub.add_parser("start-review", help="Start a specialist review of the architect plan.")
    p.add_argument("--role", required=True, choices=sorted(PLAN_REVIEW_ROLES))
    p.add_argument("--id", required=True, help="Stable agent id, e.g. frontend or developer-1.")
    p.set_defaults(handler=cmd_plan_start_review)

    p = plan_sub.add_parser("review-status", help="Summarize specialist plan review files.")
    p.set_defaults(handler=cmd_plan_review_status)

    p = plan_sub.add_parser("address-reviews", help="Start architect mode for addressing plan review feedback.")
    p.add_argument("--actor", default="architect")
    p.set_defaults(handler=cmd_plan_address_reviews)

    p = plan_sub.add_parser("list", help="List planned tasks.")
    p.set_defaults(handler=cmd_plan_list)

    # summary
    p = sub.add_parser("summary", help="Print final run summary.")
    p.set_defaults(handler=cmd_summary)

    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "uses_state", True):
        args.state = (args.state or default_state_path()).resolve()
    elif args.state is not None:
        args.state = args.state.resolve()
    result = args.handler(args)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
