#!/usr/bin/env python3
"""Swarm coordination tool for specialist agents.

WARNING: Do not edit swarm/state.json directly.
All updates must go through this tool.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import yaml  # type: ignore
except ImportError as exc:
    raise SystemExit(
        "PyYAML is required. Install with: python3 -m pip install pyyaml"
    ) from exc


VALID_TASK_STATUSES = {"todo", "in_progress", "needs_input", "done"}
ACTIVE_TASK_STATUSES = {"in_progress", "needs_input"}
VALID_ROLES = {"architect", "product", "developer", "frontend", "tester", "security"}

PROMPTS_DIR = Path(__file__).resolve().parent.parent / "prompts"

STATE_NOTICE = (
    "DO NOT EDIT THIS FILE DIRECTLY. "
    "All updates must go through the swarm tool "
    "(swarm task status, swarm task log, swarm plan set, etc.). "
    "Direct edits will be overwritten and may corrupt swarm state."
)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def default_state_path(start: Optional[Path] = None) -> Path:
    env_path = os.environ.get("SWARM_STATE_PATH")
    if env_path:
        return Path(env_path)
    current = (start or Path.cwd()).resolve()
    for candidate in [current, *current.parents]:
        p = candidate / "swarm" / "state.yaml"
        if p.exists():
            return p
        nested = sorted((candidate / "swarm").glob("*/state.yaml"))
        if len(nested) == 1:
            return nested[0]
    return current / "swarm" / "state.yaml"


def load_prompt(role: str) -> str:
    path = PROMPTS_DIR / f"{role}.md"
    if not path.exists():
        raise SystemExit(f"Prompt file not found for role {role!r}: {path}")
    return path.read_text(encoding="utf-8").strip()


# ---------------------------------------------------------------------------
# State I/O
# ---------------------------------------------------------------------------

class StateLock:
    def __init__(self, path: Path, timeout: float = 30.0, poll: float = 0.2):
        self.path = path
        self.timeout = timeout
        self.poll = poll
        self.fd: Optional[int] = None

    def acquire(self) -> None:
        deadline = time.monotonic() + self.timeout
        payload = json.dumps({"pid": os.getpid(), "createdAt": now_iso()})
        while True:
            try:
                self.fd = os.open(str(self.path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.write(self.fd, payload.encode())
                return
            except FileExistsError:
                if time.monotonic() >= deadline:
                    raise SystemExit(f"Timed out waiting for lock: {self.path}")
                time.sleep(self.poll)

    def release(self) -> None:
        if self.fd is not None:
            os.close(self.fd)
            self.fd = None
        try:
            self.path.unlink()
        except FileNotFoundError:
            pass

    def __enter__(self) -> "StateLock":
        self.acquire()
        return self

    def __exit__(self, *_: Any) -> None:
        self.release()


def load_state(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"State file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"Unexpected state shape in {path}")
    data.pop("_notice", None)
    data.setdefault("events", [])
    data.setdefault("artifacts", [])
    data.setdefault("tasks", [])
    data.setdefault("agents", {})
    data.setdefault("roles", {})
    data.setdefault("swarm", {})
    return data


def save_state(path: Path, state: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    output = {"_notice": STATE_NOTICE, **state}
    with path.open("w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)
        f.write("\n")


def with_locked_state(path: Path, handler) -> Dict[str, Any]:
    lock = StateLock(path.with_suffix(f"{path.suffix}.lock"))
    with lock:
        state = load_state(path)
        result = handler(state)
        if result.get("write", True):
            save_state(path, state)
        result.pop("write", None)
        return result


# ---------------------------------------------------------------------------
# State helpers
# ---------------------------------------------------------------------------

def find_task(state: Dict[str, Any], task_id: str) -> Dict[str, Any]:
    for task in state.get("tasks", []):
        if task.get("id") == task_id:
            return task
    raise SystemExit(f"Task not found: {task_id}")


def find_task_by_id(state: Dict[str, Any], task_id: Any) -> Optional[Dict[str, Any]]:
    for task in state.get("tasks", []):
        if isinstance(task, dict) and task.get("id") == task_id:
            return task
    return None


def append_event(state: Dict[str, Any], event_type: str, actor: str, message: str) -> Dict[str, Any]:
    event = {
        "id": f"EVT-{len(state['events']) + 1:03d}",
        "timestamp": now_iso(),
        "type": event_type,
        "actor": actor,
        "message": message,
    }
    state["events"].append(event)
    state.setdefault("swarm", {})["updatedAt"] = now_iso()
    return event


def ensure_agent(state: Dict[str, Any], agent_id: str, role: Optional[str] = None) -> Dict[str, Any]:
    agents = state.setdefault("agents", {})
    agent = agents.setdefault(agent_id, {"role": role or "developer", "status": "idle", "currentTaskId": None})
    if role and not agent.get("role"):
        agent["role"] = role
    agent.setdefault("status", "idle")
    agent.setdefault("currentTaskId", None)
    return agent


def set_agent_idle(agent: Dict[str, Any]) -> None:
    agent["status"] = "idle"
    agent["currentTaskId"] = None


def set_agent_active(agent: Dict[str, Any], task: Dict[str, Any]) -> None:
    agent["status"] = "needs_input" if task.get("status") == "needs_input" else "running"
    agent["currentTaskId"] = task.get("id")


def clear_task_refs(state: Dict[str, Any], task_id: str) -> List[str]:
    cleared = []
    for agent_id, agent in state.get("agents", {}).items():
        if isinstance(agent, dict) and agent.get("currentTaskId") == task_id:
            set_agent_idle(agent)
            cleared.append(str(agent_id))
    return cleared


def reconcile_agent(state: Dict[str, Any], agent_id: str, role: str) -> Dict[str, Any]:
    agent = ensure_agent(state, agent_id, role)
    agent["role"] = role
    repairs = []

    current_task_id = agent.get("currentTaskId")
    if current_task_id:
        current_task = find_task_by_id(state, current_task_id)
        if not current_task or current_task.get("status") not in ACTIVE_TASK_STATUSES:
            set_agent_idle(agent)
            repairs.append(f"cleared stale task ref {current_task_id}")
        elif current_task.get("ownerAgentId") in (None, "", agent_id):
            current_task["ownerAgentId"] = agent_id
            set_agent_active(agent, current_task)
            return {"agent": agent, "activeTask": current_task, "repairs": repairs}
        else:
            set_agent_idle(agent)
            repairs.append(f"cleared task {current_task_id} owned by {current_task.get('ownerAgentId')}")

    active_task = next(
        (t for t in state.get("tasks", [])
         if isinstance(t, dict) and t.get("ownerAgentId") == agent_id and t.get("status") in ACTIVE_TASK_STATUSES),
        None,
    )
    if active_task:
        set_agent_active(agent, active_task)
        return {"agent": agent, "activeTask": active_task, "repairs": repairs}

    set_agent_idle(agent)
    return {"agent": agent, "activeTask": None, "repairs": repairs}


def assign_task(state: Dict[str, Any], task: Dict[str, Any], agent_id: str) -> Dict[str, Any]:
    task["ownerAgentId"] = agent_id
    task["status"] = "in_progress"
    task["startedAt"] = task.get("startedAt") or now_iso()
    agent = ensure_agent(state, agent_id, task.get("role"))
    set_agent_active(agent, task)
    return {"agent": agent}


def recompute_phase(state: Dict[str, Any]) -> None:
    swarm = state.setdefault("swarm", {})
    tasks = state.get("tasks", [])
    if not swarm.get("planApproved", False):
        swarm["status"] = "awaiting_approval"
        return
    if tasks and all(t.get("status") == "done" for t in tasks):
        swarm["status"] = "completed"
        return
    swarm["status"] = "executing"


def ensure_evidence(task: Dict[str, Any]) -> Dict[str, Any]:
    ev = task.setdefault("evidence", {})
    ev.setdefault("summary", "")
    ev.setdefault("touchedFiles", [])
    ev.setdefault("commandsRan", [])
    ev.setdefault("results", [])
    return ev


def task_is_ready(state: Dict[str, Any], task: Dict[str, Any]) -> bool:
    if not state.get("swarm", {}).get("planApproved", False):
        return False
    if task.get("status") != "todo" or task.get("ownerAgentId"):
        return False
    for dep_id in task.get("dependsOn", []):
        dep = next((t for t in state.get("tasks", []) if t.get("id") == dep_id), None)
        if dep is None or dep.get("status") != "done":
            return False
    return True


def normalize_task(raw: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(raw, dict):
        raise SystemExit("Each task must be an object.")
    task_id = str(raw.get("id", "")).strip()
    title = str(raw.get("title", "")).strip()
    role = str(raw.get("role", "")).strip()
    if not task_id:
        raise SystemExit("Each task must have a non-empty id.")
    if not title:
        raise SystemExit(f"Task {task_id} must have a non-empty title.")
    if role not in VALID_ROLES:
        raise SystemExit(f"Task {task_id} has invalid role {role!r}.")
    status = str(raw.get("status", "todo")).strip() or "todo"
    if status not in VALID_TASK_STATUSES:
        raise SystemExit(f"Task {task_id} has invalid status {status!r}.")
    ev = raw.get("evidence") if isinstance(raw.get("evidence"), dict) else {}
    return {
        "id": task_id,
        "title": title,
        "description": str(raw.get("description", "")).strip(),
        "role": role,
        "status": status,
        "ownerAgentId": raw.get("ownerAgentId") or None,
        "dependsOn": [str(i).strip() for i in raw.get("dependsOn", []) if str(i).strip()],
        "ownedPaths": [str(i).strip() for i in raw.get("ownedPaths", []) if str(i).strip()],
        "acceptanceCriteria": [str(i).strip() for i in raw.get("acceptanceCriteria", []) if str(i).strip()],
        "implementationNotes": [str(i).strip() for i in raw.get("implementationNotes", []) if str(i).strip()],
        "evidence": {
            "summary": str(ev.get("summary", "")).strip(),
            "touchedFiles": [str(i).strip() for i in ev.get("touchedFiles", []) if str(i).strip()],
            "commandsRan": [str(i).strip() for i in ev.get("commandsRan", []) if str(i).strip()],
            "results": [str(i).strip() for i in ev.get("results", []) if str(i).strip()],
        },
        "notes": [str(i).strip() for i in raw.get("notes", []) if str(i).strip()],
        "startedAt": raw.get("startedAt") or None,
        "completedAt": raw.get("completedAt") or None,
    }


def load_tasks_payload(args: argparse.Namespace) -> List[Dict[str, Any]]:
    if getattr(args, "tasks_json", None):
        payload = json.loads(args.tasks_json)
    elif getattr(args, "file", None):
        with args.file.open("r", encoding="utf-8") as f:
            payload = json.load(f)
    else:
        raise SystemExit("Provide --file or --tasks-json.")
    tasks = payload.get("tasks") if isinstance(payload, dict) else payload
    if not isinstance(tasks, list):
        raise SystemExit("Task payload must be a list or an object with a tasks key.")
    return [normalize_task(t) for t in tasks]


def validate_task_graph(tasks: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    errors: List[str] = []
    warnings: List[str] = []
    ids = [t["id"] for t in tasks]
    id_set = set(ids)

    if len(ids) != len(id_set):
        seen: set = set()
        dups = []
        for i in ids:
            if i in seen and i not in dups:
                dups.append(i)
            seen.add(i)
        errors.append(f"Duplicate task ids: {', '.join(dups)}")

    path_owners: Dict[str, List[str]] = {}
    for t in tasks:
        tid = t["id"]
        if not t["description"]:
            warnings.append(f"{tid}: description is empty.")
        if not t["acceptanceCriteria"]:
            warnings.append(f"{tid}: acceptanceCriteria is empty.")
        for dep in t["dependsOn"]:
            if dep not in id_set:
                errors.append(f"{tid}: dependency {dep!r} does not exist.")
            if dep == tid:
                errors.append(f"{tid}: task cannot depend on itself.")
        for p in t["ownedPaths"]:
            path_owners.setdefault(p, []).append(tid)

    for p, owners in path_owners.items():
        if len(owners) > 1:
            warnings.append(f"Path {p!r} owned by multiple tasks: {', '.join(owners)}.")

    return {"errors": errors, "warnings": warnings}


def unique_strings(values: List[Any]) -> List[str]:
    seen: set = set()
    result = []
    for v in values:
        if not isinstance(v, str):
            continue
        s = v.strip()
        if s and s not in seen:
            seen.add(s)
            result.append(s)
    return result


def build_run_summary(state: Dict[str, Any]) -> Dict[str, Any]:
    tasks = state.get("tasks", [])
    completed = [t for t in tasks if t.get("status") == "done"]
    touched_files: List[Any] = []
    commands_ran: List[Any] = []
    results: List[str] = []
    task_summaries = []
    open_questions: List[str] = []

    for t in completed:
        ev = ensure_evidence(t)
        task_summaries.append({
            "id": t.get("id"),
            "title": t.get("title"),
            "summary": ev.get("summary") or "No summary recorded.",
            "ownerAgentId": t.get("ownerAgentId"),
            "completedAt": t.get("completedAt"),
        })
        touched_files.extend(ev.get("touchedFiles", []))
        commands_ran.extend(ev.get("commandsRan", []))
        results.extend(f"{t.get('id')}: {r}" for r in ev.get("results", []) if isinstance(r, str))

    for t in tasks:
        for q in t.get("notes", []):
            if isinstance(q, str) and q.strip():
                open_questions.append(f"{t.get('id')}: {q.strip()}")

    swarm = state.get("swarm", {})
    return {
        "goal": swarm.get("goal", ""),
        "status": swarm.get("status", "planning"),
        "planApproved": bool(swarm.get("planApproved", False)),
        "tasks": {"total": len(tasks), "completed": len(completed), "remaining": max(0, len(tasks) - len(completed))},
        "touchedFiles": unique_strings(touched_files),
        "commandsRan": unique_strings(commands_ran),
        "results": results,
        "completedTasks": task_summaries,
        "openQuestions": open_questions,
    }


# ---------------------------------------------------------------------------
# Command handlers
# ---------------------------------------------------------------------------

def cmd_init(args: argparse.Namespace) -> Dict[str, Any]:
    state_path = args.state
    if not state_path.exists():
        state_path.parent.mkdir(parents=True, exist_ok=True)
        initial: Dict[str, Any] = {
            "swarm": {"goal": getattr(args, "goal", "") or "", "planApproved": False, "status": "planning"},
            "tasks": [],
            "agents": {},
            "events": [],
            "artifacts": [],
            "roles": {},
        }
        save_state(state_path, initial)

    state = load_state(state_path)
    plan_path = state_path.parent / "plan.md"
    plan_exists = plan_path.exists()
    plan_ready = state.get("swarm", {}).get("planReady", False)

    if plan_exists and plan_ready:
        return {"ok": True, "role": "architect", "action": "stop", "message": "Plan is marked ready for user approval. Your work as architect is complete. Stop now."}

    if plan_exists:
        return {"ok": True, "role": "architect", "action": "stop", "message": f"Plan file exists at {plan_path} but has not been marked ready. Review it, ensure the task graph is submitted, then run: swarm plan ready"}

    goal = state.get("swarm", {}).get("goal") or "(not set — read the codebase for context)"
    prompt = load_prompt("architect")
    directive = (
        "\n\n---\n"
        "## Your Goal\n"
        f"{goal}\n\n"
        "## Steps\n"
        f"1. Read the codebase and understand what needs to be done\n"
        f"2. Write a detailed plan to `{plan_path}`\n"
        f"3. Create a task graph and save it to `swarm/tasks.json`\n"
        f"4. Run: `swarm plan validate --file swarm/tasks.json`\n"
        f"5. Run: `swarm plan set --file swarm/tasks.json`\n"
        f"6. Run: `swarm plan ready`\n"
        f"7. **Stop** — the user will review and approve before workers start\n\n"
        "**IMPORTANT: Do not edit swarm/state.json directly. "
        "All updates must go through the swarm tool.**"
    )
    return {"ok": True, "role": "architect", "action": "plan", "prompt": prompt + directive}


def cmd_join(args: argparse.Namespace) -> Dict[str, Any]:
    state = load_state(args.state)
    plan_approved = state.get("swarm", {}).get("planApproved", False)

    if not plan_approved:
        return {"ok": True, "role": args.role, "agentId": args.id, "action": "stop", "message": "The architect plan has not been approved yet. Stop and wait for the user to approve it."}

    ready = [t for t in state.get("tasks", []) if t.get("role") == args.role and task_is_ready(state, t)]

    if not ready:
        return {"ok": True, "role": args.role, "agentId": args.id, "action": "stop", "message": f"No tasks are currently ready for the '{args.role}' role. Either all tasks are complete or dependencies are not yet resolved. Stop now."}

    prompt = load_prompt(args.role)
    directive = (
        f"\n\n---\n"
        f"## Your First Action\n"
        f"You are agent `{args.id}` with role `{args.role}`.\n"
        f"There are **{len(ready)} task(s)** ready for your role.\n\n"
        f"Run:\n```\nswarm task next --role {args.role} --id {args.id}\n```\n\n"
        f"Complete the task, log evidence, mark it done, then loop back to `swarm task next`. "
        f"When no tasks remain, stop.\n\n"
        "**IMPORTANT: Do not edit swarm/state.json directly. "
        "All updates must go through the swarm tool.**"
    )
    return {"ok": True, "role": args.role, "agentId": args.id, "action": "work", "readyTaskCount": len(ready), "prompt": prompt + directive}


def cmd_task_list(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        ready = []
        for t in state.get("tasks", []):
            if getattr(args, "role", None) and t.get("role") != args.role:
                continue
            if task_is_ready(state, t):
                ready.append({"id": t.get("id"), "title": t.get("title"), "role": t.get("role"), "dependsOn": t.get("dependsOn", [])})
        return {"ok": True, "readyTasks": ready, "write": False}
    return with_locked_state(args.state, run)


def cmd_task_next(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        if not state.get("swarm", {}).get("planApproved", False):
            return {"ok": False, "error": "Plan not approved. Workers must wait.", "write": False}

        runtime = reconcile_agent(state, args.id, args.role)
        agent = runtime["agent"]
        active = runtime["activeTask"]
        if active:
            return {"ok": True, "claimed": False, "reason": "agent_already_has_active_task", "task": active, "agent": agent}

        for t in state.get("tasks", []):
            if t.get("role") != args.role or not task_is_ready(state, t):
                continue
            result = assign_task(state, t, args.id)
            recompute_phase(state)
            event = append_event(state, "task_claimed", args.id, f"{args.id} claimed {t.get('id')}.")
            return {"ok": True, "claimed": True, "task": t, "agent": result["agent"], "event": event}

        recompute_phase(state)
        return {"ok": True, "claimed": False, "reason": "no_ready_task", "message": f"No ready {args.role} tasks. Stop."}

    return with_locked_state(args.state, run)


def cmd_task_claim(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        if not state.get("swarm", {}).get("planApproved", False):
            return {"ok": False, "error": "Plan not approved.", "write": False}
        task = find_task(state, args.task_id)
        if not task_is_ready(state, task):
            return {"ok": False, "error": "Task is not ready.", "task": {"id": task.get("id"), "status": task.get("status")}, "write": False}
        result = assign_task(state, task, args.id)
        recompute_phase(state)
        event = append_event(state, "task_claimed", args.id, f"{args.id} claimed {args.task_id}.")
        return {"ok": True, "task": task, "agent": result["agent"], "event": event}
    return with_locked_state(args.state, run)


def cmd_task_status(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        actor = args.id or task.get("ownerAgentId") or task.get("role") or "agent"
        task["status"] = args.status
        if args.status == "in_progress" and not task.get("startedAt"):
            task["startedAt"] = now_iso()
        if args.status == "done":
            task["completedAt"] = now_iso()
        if getattr(args, "summary", None):
            ensure_evidence(task)["summary"] = args.summary
        if task.get("ownerAgentId"):
            agent = ensure_agent(state, task["ownerAgentId"], task.get("role"))
            if args.status == "in_progress":
                agent["status"] = "running"
                agent["currentTaskId"] = args.task_id
            elif args.status == "needs_input":
                agent["status"] = "needs_input"
                agent["currentTaskId"] = args.task_id
        cleared = []
        if args.status not in ACTIVE_TASK_STATUSES:
            cleared = clear_task_refs(state, args.task_id)
        recompute_phase(state)
        event = append_event(state, "task_status_changed", actor, f"{actor} moved {args.task_id} to {args.status}.")
        return {"ok": True, "task": task, "event": event, "clearedAgents": cleared}
    return with_locked_state(args.state, run)


def cmd_task_log(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        ev = ensure_evidence(task)
        if getattr(args, "summary", None):
            ev["summary"] = args.summary
        ev["touchedFiles"].extend(args.file or [])
        ev["commandsRan"].extend(args.command or [])
        ev["results"].extend(args.result or [])
        event = append_event(state, "task_evidence_appended", args.id, f"{args.id} logged evidence for {args.task_id}.")
        return {"ok": True, "task": task, "event": event}
    return with_locked_state(args.state, run)


def cmd_task_note(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        task = find_task(state, args.task_id)
        task.setdefault("notes", []).append(args.note)
        event = append_event(state, "task_note_added", args.id, f"{args.id} added note to {args.task_id}.")
        return {"ok": True, "task": task, "event": event}
    return with_locked_state(args.state, run)


def cmd_plan_validate(args: argparse.Namespace) -> Dict[str, Any]:
    tasks = load_tasks_payload(args)
    v = validate_task_graph(tasks)
    return {"ok": len(v["errors"]) == 0, "taskCount": len(tasks), "errors": v["errors"], "warnings": v["warnings"]}


def cmd_plan_set(args: argparse.Namespace) -> Dict[str, Any]:
    next_tasks = load_tasks_payload(args)
    v = validate_task_graph(next_tasks)
    if v["errors"]:
        return {"ok": False, "errors": v["errors"], "warnings": v["warnings"]}

    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        if state.get("swarm", {}).get("planApproved", False) and not getattr(args, "force", False):
            return {"ok": False, "error": "Plan already approved. Use --force to override.", "write": False}
        state["tasks"] = next_tasks
        swarm = state.setdefault("swarm", {})
        swarm.update({"planReady": False, "planReadyAt": None, "planReadyBy": None, "taskGraphReplacedAt": now_iso()})
        for agent in state.get("agents", {}).values():
            if isinstance(agent, dict):
                agent.update({"status": "idle", "currentTaskId": None})
        recompute_phase(state)
        event = append_event(state, "tasks_replaced", args.actor, f"{args.actor} set task graph ({len(next_tasks)} tasks).")
        return {"ok": True, "taskCount": len(next_tasks), "warnings": v["warnings"], "event": event}

    return with_locked_state(args.state, run)


def cmd_plan_ready(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        swarm = state.setdefault("swarm", {})
        if swarm.get("planApproved", False) and not getattr(args, "force", False):
            return {"ok": False, "error": "Plan already approved.", "write": False}

        tasks = [normalize_task(t) for t in state.get("tasks", [])]
        v = validate_task_graph(tasks)
        if v["errors"]:
            return {"ok": False, "error": "Task graph has errors. Fix before marking ready.", "errors": v["errors"]}

        task_graph_set = bool(swarm.get("taskGraphReplacedAt")) or any(
            e.get("type") == "tasks_replaced" for e in state.get("events", [])
        )
        if not task_graph_set and not getattr(args, "force", False):
            return {"ok": False, "error": "Run `swarm plan set` before marking ready."}

        plan_path = getattr(args, "plan", None) or args.state.parent / "plan.md"
        warnings = list(v["warnings"])
        if not plan_path.exists():
            if not getattr(args, "force", False):
                return {"ok": False, "error": f"Plan file not found: {plan_path}.", "write": False}
            warnings.append(f"Plan file not found: {plan_path}.")

        swarm.update({"planReady": True, "planReadyAt": now_iso(), "planReadyBy": args.actor})
        event = append_event(state, "plan_ready", args.actor, f"{args.actor} marked plan ready for review.")
        return {"ok": True, "planReady": True, "warnings": warnings, "event": event}

    return with_locked_state(args.state, run)


def cmd_summary(args: argparse.Namespace) -> Dict[str, Any]:
    def run(state: Dict[str, Any]) -> Dict[str, Any]:
        return {"ok": True, "summary": build_run_summary(state), "write": False}
    return with_locked_state(args.state, run)


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

TOP_LEVEL_HELP = """\
Swarm tool — all state mutations go through here. Never edit state.json directly.

Entry points (return full system prompt for the agent):
  swarm init [--goal "..."]
  swarm join --role developer --id developer-1

Task commands:
  swarm task next   --role developer --id developer-1
  swarm task claim  --task-id T3 --id developer-1
  swarm task status --task-id T3 --status done --id developer-1
  swarm task log    --task-id T3 --id developer-1 --summary "..." --file src/foo.ts --command "npm test" --result "Passed"
  swarm task note   --task-id T3 --id developer-1 --note "Blocked on X"
  swarm task list   --role developer

Plan commands (architect only):
  swarm plan validate --file swarm/tasks.json
  swarm plan set      --file swarm/tasks.json
  swarm plan ready

Run summary:
  swarm summary
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Swarm coordination tool",
        epilog=TOP_LEVEL_HELP,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--state",
        type=Path,
        default=default_state_path(),
        help="Path to state file (auto-detected from cwd).",
    )

    sub = parser.add_subparsers(dest="group", required=True)

    # init
    p = sub.add_parser("init", help="Start swarm as architect, returns full prompt.")
    p.add_argument("--goal", help="Goal for the swarm (stored in state).")
    p.set_defaults(handler=cmd_init)

    # join
    p = sub.add_parser("join", help="Join swarm as worker, returns full role prompt.")
    p.add_argument("--role", required=True, choices=sorted(VALID_ROLES))
    p.add_argument("--id", required=True, help="Stable agent id, e.g. developer-1.")
    p.set_defaults(handler=cmd_join)

    # task
    task_p = sub.add_parser("task", help="Task operations.")
    task_sub = task_p.add_subparsers(dest="action", required=True)

    p = task_sub.add_parser("next", help="Claim the next ready task for your role.")
    p.add_argument("--role", required=True, choices=sorted(VALID_ROLES))
    p.add_argument("--id", required=True)
    p.set_defaults(handler=cmd_task_next)

    p = task_sub.add_parser("claim", help="Claim a specific task by ID.")
    p.add_argument("--task-id", required=True)
    p.add_argument("--id", required=True, help="Agent id.")
    p.set_defaults(handler=cmd_task_claim)

    p = task_sub.add_parser("status", help="Update task status.")
    p.add_argument("--task-id", required=True)
    p.add_argument("--status", required=True, choices=sorted(VALID_TASK_STATUSES))
    p.add_argument("--id", help="Agent id.")
    p.add_argument("--summary", help="Completion summary (used when status=done).")
    p.set_defaults(handler=cmd_task_status)

    p = task_sub.add_parser("log", help="Log work evidence (files, commands, results).")
    p.add_argument("--task-id", required=True)
    p.add_argument("--id", required=True, help="Agent id.")
    p.add_argument("--summary")
    p.add_argument("--file", action="append", metavar="PATH")
    p.add_argument("--command", action="append", metavar="CMD")
    p.add_argument("--result", action="append", metavar="RESULT")
    p.set_defaults(handler=cmd_task_log)

    p = task_sub.add_parser("note", help="Add a freeform note to a task.")
    p.add_argument("--task-id", required=True)
    p.add_argument("--id", required=True, help="Agent id.")
    p.add_argument("--note", required=True)
    p.set_defaults(handler=cmd_task_note)

    p = task_sub.add_parser("list", help="List ready tasks for a role.")
    p.add_argument("--role", choices=sorted(VALID_ROLES))
    p.set_defaults(handler=cmd_task_list)

    # plan
    plan_p = sub.add_parser("plan", help="Plan operations (architect only).")
    plan_sub = plan_p.add_subparsers(dest="action", required=True)

    p = plan_sub.add_parser("validate", help="Validate task graph JSON before submitting.")
    p.add_argument("--file", type=Path)
    p.add_argument("--tasks-json")
    p.set_defaults(handler=cmd_plan_validate)

    p = plan_sub.add_parser("set", help="Submit a new task graph.")
    p.add_argument("--actor", default="architect")
    p.add_argument("--file", type=Path)
    p.add_argument("--tasks-json")
    p.add_argument("--force", action="store_true")
    p.set_defaults(handler=cmd_plan_set)

    p = plan_sub.add_parser("ready", help="Mark plan ready for user approval.")
    p.add_argument("--actor", default="architect")
    p.add_argument("--plan", type=Path)
    p.add_argument("--force", action="store_true")
    p.set_defaults(handler=cmd_plan_ready)

    # summary
    p = sub.add_parser("summary", help="Print final run summary.")
    p.set_defaults(handler=cmd_summary)

    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.state = args.state.resolve()
    result = args.handler(args)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
