// The start-up pass over what earlier builds wrote: the one-time scan lists
// it, and every listed entry moves onto the Studio launcher in place, with
// everything around it left exactly as it was. Fixtures are a temporary home
// and repository; nothing here reads this machine's own.

import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { mkdir, mkdtemp, readFile, realpath, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { test } from 'vitest'

import { runGitCommand } from '../git-utils'
import { prepareStudioIntegrations } from './integration-boot'
import {
  migrateCodexGatewayBlock,
  migrateGatewayServer,
  migrateHookCommand,
  parseLegacyHookCommand,
  splitCommandLine,
} from './integration-migrate'
import { scanForIntegrations } from './integration-scan'
import { launcherRefForHome } from './launcher'
import { createIntegrationLedger } from './ledger'

const APP_EXE = '/Applications/SprintEngine Studio.app/Contents/MacOS/SprintEngine Studio'
const BRIDGE = '/Applications/SprintEngine Studio.app/Contents/Resources/automation/mcp-stdio-bridge.mjs'
const SOCKET = '/Users/dev/Library/Application Support/SprintEngine Studio/agent-state.sock'

async function json(path: string): Promise<any> {
  return JSON.parse(await readFile(path, 'utf8'))
}

async function write(path: string, content: string | object): Promise<void> {
  await mkdir(join(path, '..'), { recursive: true })
  await writeFile(path, typeof content === 'string' ? content : `${JSON.stringify(content, null, 2)}\n`)
}

/** A repository and a home as an earlier build left them, with the person's own content around ours. */
async function legacyWorld() {
  const root = await mkdtemp(join(tmpdir(), 'sprintengine-boot-'))
  const home = join(root, 'home')
  const repo = join(root, 'repo')
  await mkdir(repo, { recursive: true })
  for (const args of [
    ['init', '-q'],
    ['-c', 'user.email=dev@example.com', '-c', 'user.name=dev', 'commit', '-q', '--allow-empty', '-m', 'seed'],
  ]) {
    assert.ok((await runGitCommand(repo, args)).ok)
  }
  const reporter = `${repo}/.sprintengine/hooks/agent-state.mjs`
  const legacyHook = `node "${reporter}" --socket "${SOCKET}"`
  const legacyStatusLine = `node "${repo}/.sprintengine/hooks/status-line.mjs" --socket "${SOCKET}" --wrap "eyJjb21tYW5kIjoibHMifQ=="`
  const legacyGateway = {
    type: 'stdio',
    command: APP_EXE,
    args: [BRIDGE],
    env: { ELECTRON_RUN_AS_NODE: '1', SPRINTENGINE_USER_DATA_DIR: '/Users/dev/ud' },
  }

  await write(join(repo, '.sprintengine', 'hooks', 'agent-state.mjs'), '// old copy\n')
  await write(join(repo, '.sprintengine', 'hooks', 'status-line.mjs'), '// old copy\n')
  await write(join(repo, '.sprintengine', 'hooks', '.gitignore'), '*\n')
  await write(join(repo, '.claude', 'settings.local.json'), {
    permissions: { allow: ['Bash(ls:*)'] },
    hooks: {
      Stop: [
        {
          hooks: [
            { type: 'command', command: 'say done' },
            { type: 'command', command: legacyHook, _sprintengine: 'sprintengine-agent-state' },
          ],
        },
      ],
    },
    statusLine: {
      type: 'command',
      command: legacyStatusLine,
      _sprintengine: true,
      _sprintengineWrapped: { type: 'command', command: 'ls' },
    },
    enabledMcpjsonServers: ['theirs', 'sprintengine-studio'],
    extraKnownMarketplaces: {
      'sprintengine-studio': { source: { source: 'directory', path: `${repo}/.sprintengine/studio-plugin` } },
    },
  })
  await write(join(repo, '.claude', 'settings.json'), {
    enabledPlugins: { 'theirs@theirs': true, 'sprintengine-studio@sprintengine-studio': true },
  })
  await write(join(repo, '.mcp.json'), {
    mcpServers: { theirs: { command: 'npx', args: ['theirs'] }, 'sprintengine-studio': legacyGateway },
  })
  await write(join(repo, '.cursor', 'mcp.json'), { mcpServers: { 'sprintengine-studio': legacyGateway } })
  await write(join(repo, '.cursor', 'hooks.json'), {
    version: 1,
    hooks: { stop: [{ command: 'notify-send hi' }, { command: legacyHook }] },
  })
  await write(
    join(repo, '.codex', 'config.toml'),
    [
      'model = "gpt-5-codex"',
      '',
      '# >>> sprintengine agent-state hooks managed',
      '[[hooks.Stop]]',
      '[[hooks.Stop.hooks]]',
      'type = "command"',
      `command = ${JSON.stringify(legacyHook)}`,
      '# <<< sprintengine agent-state hooks managed',
      '',
      '# >>> sprintengine mcp managed',
      '# This section is generated by SprintEngine Settings. Edit MCPs in SprintEngine or remove this block.',
      '',
      '[mcp_servers.theirs]',
      'command = "npx"',
      'enabled = true',
      '',
      '[mcp_servers.sprintengine-studio]',
      `command = ${JSON.stringify(APP_EXE)}`,
      `args = [${JSON.stringify(BRIDGE)}]`,
      'env = { "ELECTRON_RUN_AS_NODE" = "1", "SPRINTENGINE_USER_DATA_DIR" = "/Users/dev/ud" }',
      'enabled = true',
      '# <<< sprintengine mcp managed',
      '',
    ].join('\n'),
  )
  await write(join(repo, 'opencode.json'), {
    mcp: {
      'sprintengine-studio': { type: 'local', command: [APP_EXE, BRIDGE], environment: { ELECTRON_RUN_AS_NODE: '1' } },
    },
  })
  await write(join(repo, '.grok', 'hooks', 'sprintengine-agent-state.json'), {
    hooks: { Stop: [{ hooks: [{ type: 'command', command: legacyHook }] }] },
  })
  await write(join(repo, '.agents', 'skills', 'studio-backlog', 'SKILL.md'), '# skill\n')
  await write(join(repo, '.agents', 'skills', 'studio-backlog', '.sprintengine-skill.json'), {
    sourceId: 'sprintengine-studio',
    skillId: 'studio-backlog',
    commitSha: '1',
  })
  await write(join(repo, '.agents', 'skills', 'mine', 'SKILL.md'), '# mine\n')
  await write(join(repo, '.git', 'info', 'exclude'), '# theirs\n.mcp.json\n.codex/config.toml\n')
  await write(
    join(home, '.kimi-code', 'config.toml'),
    [
      'default_model = "k2"',
      '# >>> sprintengine agent-state hooks managed',
      '[[hooks]]',
      'event = "Stop"',
      `command = ${JSON.stringify(`node "${home}/.sprintengine/hooks/agent-state.mjs" --socket "${SOCKET}"`)}`,
      '# <<< sprintengine agent-state hooks managed',
      '',
    ].join('\n'),
  )
  await write(join(home, '.sprintengine', 'hooks', 'agent-state.mjs'), '// old home copy\n')
  return { root, home, repo }
}

test('the first start lists what an earlier build wrote and moves every entry onto the launcher, leaving the rest alone', async () => {
  const { root, home, repo } = await legacyWorld()
  const ledger = createIntegrationLedger({ path: join(root, 'userData', 'integration-ledger.json') })
  const launcher = launcherRefForHome(home, 'posix').path
  const pointer = {
    node: process.execPath,
    runAsNode: false,
    payload: join(process.cwd(), 'resources'),
    packaged: false,
  }
  const result = await prepareStudioIntegrations({
    ledger,
    home,
    shell: 'posix',
    pointer,
    listRoots: () => [{ path: repo, hostId: 'local' }],
    env: {},
  })
  assert.ok(existsSync(launcher), 'the launcher is written')

  const kinds = new Set((await ledger.list()).map((entry) => `${entry.kind}:${entry.marker}`))
  for (const expected of [
    'agent-state-hooks:settings-json',
    'status-line:statusLine',
    'mcp-approval:enabledMcpjsonServers.sprintengine-studio',
    'claude-plugin-setting:extraKnownMarketplaces.sprintengine-studio',
    'claude-plugin-setting:enabledPlugins.sprintengine-studio@sprintengine-studio',
    'mcp-gateway:mcpServers.sprintengine-studio',
    'mcp-gateway:mcp.sprintengine-studio',
    'agent-state-hooks:toml-block',
    'agent-state-hooks:flat-hooks-json',
    'agent-state-hooks:owned-json',
    'agent-state-hooks:toml-array-block',
    'skill-copy:provenance:sprintengine-studio',
    'git-exclude:legacy-shared-pair',
    'launcher:owned',
  ]) {
    assert.ok(kinds.has(expected), `the scan lists ${expected}; got ${[...kinds].join(', ')}`)
  }
  assert.ok(result.scanned && result.scanned > 10)
  assert.ok(![...kinds].some((kind) => kind.includes('mine')), "the person's own skill is not ours")

  // Every command now runs the launcher; the person's content is untouched.
  const local = await json(join(repo, '.claude', 'settings.local.json'))
  assert.deepEqual(local.permissions, { allow: ['Bash(ls:*)'] })
  const stop = local.hooks.Stop[0].hooks
  assert.equal(stop[0].command, 'say done')
  assert.equal(stop[1].command, `/bin/sh '${launcher}' agent-state --socket '${SOCKET}'`)
  assert.equal(
    local.statusLine.command,
    `/bin/sh '${launcher}' status-line --socket '${SOCKET}' --wrap "eyJjb21tYW5kIjoibHMifQ=="`,
    'the wrapped status line rides along',
  )
  assert.deepEqual(local.statusLine._sprintengineWrapped, { type: 'command', command: 'ls' })

  const mcp = await json(join(repo, '.mcp.json'))
  assert.deepEqual(mcp.mcpServers.theirs, { command: 'npx', args: ['theirs'] })
  assert.deepEqual(mcp.mcpServers['sprintengine-studio'], {
    type: 'stdio',
    command: '/bin/sh',
    args: [launcher, 'mcp'],
    env: { SPRINTENGINE_USER_DATA_DIR: '/Users/dev/ud' },
  })
  assert.equal((await json(join(repo, '.cursor', 'mcp.json'))).mcpServers['sprintengine-studio'].command, '/bin/sh')
  const cursorHooks = await json(join(repo, '.cursor', 'hooks.json'))
  assert.equal(cursorHooks.hooks.stop[0].command, 'notify-send hi')
  assert.ok(cursorHooks.hooks.stop[1].command.includes(`'${launcher}' agent-state`))
  assert.ok(
    (await json(join(repo, '.grok', 'hooks', 'sprintengine-agent-state.json'))).hooks.Stop[0].hooks[0].command.includes(
      launcher,
    ),
  )
  assert.deepEqual((await json(join(repo, 'opencode.json'))).mcp['sprintengine-studio'], {
    type: 'local',
    command: ['/bin/sh', launcher, 'mcp'],
  })

  const codex = await readFile(join(repo, '.codex', 'config.toml'), 'utf8')
  assert.ok(codex.startsWith('model = "gpt-5-codex"\n'))
  assert.ok(
    codex.includes('[mcp_servers.theirs]\ncommand = "npx"\nenabled = true'),
    'a synced server of theirs is untouched',
  )
  assert.ok(
    codex.includes(
      `command = "/bin/sh"\nargs = [${JSON.stringify(launcher)}, "mcp"]\nenv = { "SPRINTENGINE_USER_DATA_DIR" = "/Users/dev/ud" }`,
    ),
    codex,
  )
  assert.ok(codex.includes(JSON.stringify(`/bin/sh '${launcher}' agent-state --socket '${SOCKET}'`)), codex)
  assert.ok(!codex.includes(APP_EXE) && !codex.includes('node \\"'), 'nothing names the app or a bare node any more')

  const kimi = await readFile(join(home, '.kimi-code', 'config.toml'), 'utf8')
  assert.ok(kimi.startsWith('default_model = "k2"\n'))
  assert.ok(kimi.includes(`'${launcher}' agent-state`), kimi)

  // The reporter copies nothing names any more are gone, with their directory.
  assert.equal(existsSync(join(repo, '.sprintengine')), false)
  assert.equal(existsSync(join(home, '.sprintengine', 'hooks')), false)
  assert.ok(result.removedScripts >= 3)

  // A second start lists nothing new and changes nothing.
  const snapshot = await readFile(join(repo, '.codex', 'config.toml'), 'utf8')
  const again = await prepareStudioIntegrations({
    ledger,
    home,
    shell: 'posix',
    pointer,
    listRoots: () => [{ path: repo, hostId: 'local' }],
    env: {},
  })
  assert.equal(again.scanned, null, 'the scan runs once')
  assert.equal(again.migrated, 0)
  assert.equal(await readFile(join(repo, '.codex', 'config.toml'), 'utf8'), snapshot)
})

test('a reporter copy another registration still names is kept', async () => {
  const { root, home, repo } = await legacyWorld()
  // A registration nobody listed — in a shape the scan does not claim — still
  // names the copy, and a CLI still runs it.
  await write(join(repo, '.claude', 'settings.json'), {
    hooks: {
      Stop: [{ hooks: [{ type: 'command', command: `node "${repo}/.sprintengine/hooks/agent-state.mjs" --by-hand` }] }],
    },
  })
  const ledger = createIntegrationLedger({ path: join(root, 'integration-ledger.json') })
  await prepareStudioIntegrations({
    ledger,
    home,
    shell: 'posix',
    pointer: { node: process.execPath, runAsNode: false, payload: join(process.cwd(), 'resources'), packaged: false },
    listRoots: () => [{ path: repo, hostId: 'local' }],
    env: {},
  })
  assert.equal(existsSync(join(repo, '.sprintengine', 'hooks', 'agent-state.mjs')), true)
})

test('legacy commands are taken apart the way the shell read them', () => {
  assert.deepEqual(splitCommandLine(`env A='x y' '/n/node' '/r/.sprintengine/hooks/agent-state.mjs' --socket '/s'`), [
    'env',
    'A=x y',
    '/n/node',
    '/r/.sprintengine/hooks/agent-state.mjs',
    '--socket',
    '/s',
  ])
  assert.deepEqual(splitCommandLine('node "C:/r/.sprintengine/hooks/agent-state.mjs" --socket "\\\\.\\pipe\\x"'), [
    'node',
    'C:/r/.sprintengine/hooks/agent-state.mjs',
    '--socket',
    '\\\\.\\pipe\\x',
  ])
  assert.equal(splitCommandLine('node "unterminated'), null)
  assert.equal(parseLegacyHookCommand('echo "/r/.sprintengine/hooks/agent-state.mjs"'), null, 'only node or env')
  assert.equal(parseLegacyHookCommand('node "/r/other.mjs" --socket "/s"'), null, 'only our scripts')
  assert.equal(
    parseLegacyHookCommand('node ".sprintengine/hooks/knowledge-activity.mjs" --knowledge-root "docs"')?.target,
    'knowledge-activity',
  )
})

test("a distribution's command moves to that distribution's launcher, found from the Node it ran", () => {
  const context = { localLauncher: launcherRefForHome('C:\\Users\\dev', 'windows') }
  const wsl = `env '/home/dev/.local/share/sprintengine-studio/runtime/node-v24.21.0/bin/node' '/home/dev/repo/.sprintengine/hooks/agent-state.mjs' --socket '/run/user/1000/sprintengine/abc/agent.sock'`
  assert.equal(
    migrateHookCommand(wsl, context),
    `/bin/sh '/home/dev/.sprintengine/bin/studio-run' agent-state --socket '/run/user/1000/sprintengine/abc/agent.sock'`,
  )
  const windows = 'node "C:/r/.sprintengine/hooks/agent-state.mjs" --socket "\\\\.\\pipe\\sprintengine-agent-state-abc"'
  assert.equal(
    migrateHookCommand(windows, context),
    'C:/Users/dev/.sprintengine/bin/studio-run.cmd agent-state --socket "\\\\.\\pipe\\sprintengine-agent-state-abc"',
  )
  assert.equal(
    migrateHookCommand("env '/usr/bin/node' '/r/.sprintengine/hooks/agent-state.mjs' --socket '/s'", context),
    null,
    'an unknown Node is left as it is',
  )

  assert.deepEqual(
    migrateGatewayServer(
      {
        command: '/home/dev/.local/share/sprintengine-studio/runtime/node-v24.21.0/bin/node',
        args: ['/home/dev/.local/share/sprintengine-studio/0.4.0/automation/mcp-stdio-bridge.mjs'],
        env: { ELECTRON_RUN_AS_NODE: '1', SPRINTENGINE_USER_DATA_DIR: '/run/user/1000/x' },
      },
      context,
    ),
    {
      command: '/bin/sh',
      args: ['/home/dev/.sprintengine/bin/studio-run', 'mcp'],
      env: { SPRINTENGINE_USER_DATA_DIR: '/run/user/1000/x' },
    },
  )
  assert.equal(migrateGatewayServer({ command: 'npx', args: ['server'] }, context), null)
  assert.equal(migrateCodexGatewayBlock('model = "x"\n', context), null)
})

test('the scan reaches the worktrees of a repository it was pointed at', async () => {
  const { root, repo } = await legacyWorld()
  assert.ok((await runGitCommand(repo, ['worktree', 'add', '-q', join(root, 'wt')])).ok)
  // Git lists it by its real path (macOS's temporary directory is a symlink).
  const worktree = await realpath(join(root, 'wt'))
  await write(join(worktree, '.mcp.json'), {
    mcpServers: { 'sprintengine-studio': { command: APP_EXE, args: [BRIDGE], env: { ELECTRON_RUN_AS_NODE: '1' } } },
  })
  const found = await scanForIntegrations({ roots: [{ path: repo, hostId: 'local' }], homes: [], env: {} })
  assert.ok(
    found.some((entry) => entry.kind === 'mcp-gateway' && entry.path.startsWith(worktree)),
    'the worktree was read',
  )
})
