import { mkdir, stat, appendFile, readFile } from 'fs/promises';
import type { ConversationEvent, ConversationInterruptInput, ConversationListSessionsInput, ConversationListSessionsResult, ConversationRespondToRequestInput, ConversationSendTurnInput, ConversationSessionActionResult, ConversationSetPermissionInput, ConversationStartSessionInput, ConversationStartSessionResult, ConversationStopSessionInput, ConversationTranscriptInput, ConversationTranscriptResult } from '../shared/conversation-runtime';
import { getConversationProviderById } from './plugin-registry-instance';
import { ProviderSecretStore } from './secret-store';
import type { TerminalRootInfo } from './workspace-memory';
import { type ConversationProviderAdapter } from './providers/mock-conversation-provider';
type ConversationRuntimeOptions = {
    adapters?: ConversationProviderAdapter[];
    secretStore?: Pick<ProviderSecretStore, 'getStatus'> & Partial<Pick<ProviderSecretStore, 'resolveSecret'>>;
    getProviderById?: typeof getConversationProviderById;
    stat?: typeof stat;
    mkdir?: typeof mkdir;
    appendFile?: typeof appendFile;
    readFile?: typeof readFile;
    now?: () => number;
    randomId?: () => string;
    prepareStudioMcp?: (input: {
        workspaceRoot: string;
        workspaceId: string;
        agentId: string;
    }) => Promise<{
        ok: true;
    } | {
        ok: false;
        message: string;
    }>;
};
type ConversationRuntimeListener = (event: ConversationEvent) => void;
export declare class ConversationRuntime {
    private readonly adapters;
    private readonly secretStore;
    private readonly getProviderById;
    private readonly stat;
    private readonly mkdir;
    private readonly appendFile;
    private readonly readFile;
    private readonly now;
    private readonly randomId;
    private readonly prepareStudioMcp?;
    private readonly sessions;
    private readonly listeners;
    private eventSequence;
    private readonly eventEpoch;
    private idleThresholdMs;
    private idleSweepTimer;
    constructor(options?: ConversationRuntimeOptions);
    onEvent(listener: ConversationRuntimeListener): () => void;
    startSession(input: ConversationStartSessionInput): Promise<ConversationStartSessionResult>;
    sendTurn(input: ConversationSendTurnInput): Promise<ConversationSessionActionResult>;
    respondToRequest(input: ConversationRespondToRequestInput): Promise<ConversationSessionActionResult>;
    setPermission(input: ConversationSetPermissionInput): Promise<ConversationSessionActionResult>;
    interrupt(input: ConversationInterruptInput): Promise<ConversationSessionActionResult>;
    stopSession(input: ConversationStopSessionInput): Promise<ConversationSessionActionResult>;
    listSessions(input?: ConversationListSessionsInput): ConversationListSessionsResult;
    setIdleThresholdMs(value: unknown): void;
    startIdleSweep(): void;
    stopIdleSweep(): void;
    sweepIdleSessions(now?: number): string[];
    listLiveConversationRoots(): TerminalRootInfo[];
    shutdown(): Promise<void>;
    private validateStartInput;
    private getAdapterForProviderId;
    private resolveSecret;
    private cancelActiveTurn;
    private emitAll;
    private emit;
    private trackStatefulSessionEvent;
    private enqueueContinuationEvent;
    private processContinuationEvent;
    private shouldSuppressEvent;
    private eventForSession;
    private applyTurnState;
    private persistEvent;
    private transcriptPath;
    readTranscript(input: ConversationTranscriptInput): Promise<ConversationTranscriptResult>;
    private readResumeCursor;
    private toSummary;
}
export {};
