import type { GitCommandResult, GitRepoOperation, GitResetMode } from './git';
export declare function commitGitChanges(repoRoot: string, message: string): Promise<GitCommandResult>;
export declare function pushGitBranch(repoRoot: string): Promise<GitCommandResult>;
export declare function fetchGitRemotes(repoRoot: string): Promise<GitCommandResult>;
export declare function pullGitBranchWithStash(repoRoot: string): Promise<GitCommandResult>;
export declare function switchGitBranch(repoRoot: string, branchName: string): Promise<GitCommandResult>;
export declare function mergeGitRef(repoRoot: string, ref: string): Promise<GitCommandResult>;
export declare function rebaseGitBranch(repoRoot: string, ontoRef: string): Promise<GitCommandResult>;
export declare function cherryPickGitCommit(repoRoot: string, commitHash: string): Promise<GitCommandResult>;
export declare function revertGitCommit(repoRoot: string, commitHash: string): Promise<GitCommandResult>;
export declare function resetGitBranchToCommit(repoRoot: string, commitHash: string, mode: GitResetMode): Promise<GitCommandResult>;
export declare function deleteGitBranch(repoRoot: string, branchName: string, force?: boolean): Promise<GitCommandResult>;
export declare function renameGitBranch(repoRoot: string, branchName: string, newName: string): Promise<GitCommandResult>;
export declare function continueGitOperation(repoRoot: string, operation: GitRepoOperation): Promise<GitCommandResult>;
export declare function abortGitOperation(repoRoot: string, operation: GitRepoOperation): Promise<GitCommandResult>;
export declare function checkoutGitCommit(repoRoot: string, commitHash: string): Promise<GitCommandResult>;
export declare function createGitBranchFromCommit(repoRoot: string, branchName: string, commitHash: string): Promise<GitCommandResult>;
export declare function checkoutGitCommitAsBranch(repoRoot: string, branchName: string, commitHash: string): Promise<GitCommandResult>;
export declare function createGitTagFromCommit(repoRoot: string, tagName: string, commitHash: string): Promise<GitCommandResult>;
