import type { WebContents } from 'electron';
import type * as pty from 'node-pty';
import type { AgentCli, AgentExecutionMode, AgentSessionIdentity, AgentState, SessionActivity, SessionPrompt, TerminalKind, TerminalPathStyle, TerminalSessionSnapshot } from '../shared/electron-api';
import type { AgentLaunchRecord } from '../shared/agent-launch';
export type TerminalSize = {
    cols: number;
    rows: number;
};
type FailedTerminalSessionInput = {
    sessionId: string;
    sender?: WebContents;
    message: string;
    at?: number;
    exitCode?: number;
    kind?: TerminalKind;
    pathStyle?: TerminalPathStyle;
    workspaceId?: string;
    agentId?: string;
    agentName?: string;
    terminalId?: string;
    cli?: AgentCli;
    cwd?: string;
    sprintEngineStatePath?: string;
    sprintEngineMcpRunId?: string;
    sprintEngineRole?: string;
    executionMode?: AgentExecutionMode;
    worktreeId?: string;
    worktreePath?: string;
    agentSession?: AgentSessionIdentity;
    visible?: boolean;
    lastOutputAt?: number | null;
    lastInputAt?: number | null;
};
export type TerminalSession = {
    sessionId: string;
    process: pty.IPty;
    sender: WebContents;
    isReady: boolean;
    hasExited: boolean;
    exitedAt: number | null;
    exitCode?: number;
    isDisposed: boolean;
    suspended?: boolean;
    suspending?: boolean;
    reapExempt?: boolean;
    idleTimer?: ReturnType<typeof setTimeout>;
    agentStallTimer?: ReturnType<typeof setTimeout>;
    activity: SessionActivity;
    agentState?: AgentState;
    lastPrompt?: SessionPrompt;
    pendingWakeupAt?: number | null;
    outputChunks: string[];
    outputChunkBytes: number[];
    outputChunkStart: number;
    outputBytes: number;
    outputLength: number;
    replaySnapshot?: string;
    kind: TerminalKind;
    pathStyle?: TerminalPathStyle;
    workspaceId?: string;
    agentId?: string;
    agentName?: string;
    terminalId?: string;
    cliSessionId?: string;
    cli?: AgentCli;
    cwd?: string;
    sprintEngineStatePath?: string;
    sprintEngineMcpRunId?: string;
    sprintEngineRole?: string;
    executionMode?: AgentExecutionMode;
    worktreeId?: string;
    worktreePath?: string;
    agentSession?: AgentSessionIdentity;
    agentRecord?: AgentLaunchRecord;
    visible: boolean;
    startedAt: number;
    lastOutputAt: number | null;
    lastInputAt: number | null;
    lastVisibleAt: number | null;
    pendingResize?: TerminalSize;
    appliedCols?: number;
    appliedRows?: number;
    repaintGraceUntil?: number;
    startupScriptPath?: string;
};
export declare const DEFAULT_IDLE_POLICY: {
    readonly flipToIdleAfterMs: 3000;
};
export declare function getTerminalSize(cols: number, rows: number): TerminalSize;
export declare function isTerminalProcessAlive(session: TerminalSession): boolean;
export declare function clearTerminalIdleTimer(session: TerminalSession): void;
export declare function clearAgentStallTimer(session: TerminalSession): void;
export declare function createInitialAgentState(kind: TerminalKind, startedAt: number): AgentState | undefined;
export declare function getTerminalIdleTimeoutMs(_session: TerminalSession): number;
export declare function createInitialTerminalActivity(startedAt: number): SessionActivity;
export declare function transitionTerminalActivity(session: TerminalSession, next: SessionActivity): boolean;
export declare function recordTerminalInput(session: TerminalSession, at?: number): void;
export declare function recordTerminalVisibility(session: TerminalSession, visible: boolean, at?: number): void;
export declare const STALE_TERMINAL_MAX_UNSEEN_MS: number;
export declare function getTerminalLastSeenAt(session: TerminalSession): number;
export declare function isTerminalSessionStale(session: TerminalSession, now?: number, maxUnseenMs?: number): boolean;
export declare function markTerminalExited(session: TerminalSession, exitCode: number, at?: number): void;
export declare function markTerminalFailed(session: TerminalSession, exitCode: number, message: string | undefined, at?: number): void;
export declare function createFailedTerminalSession(input: FailedTerminalSessionInput): TerminalSession;
type SuspendedPlaceholderSessionInput = {
    sessionId: string;
    sender?: WebContents;
    savedAt: number;
    kind?: TerminalKind;
    workspaceId?: string;
    agentId?: string;
    terminalId?: string;
    cli?: AgentCli;
    cliSessionId?: string;
    cwd?: string;
    executionMode?: AgentExecutionMode;
    worktreeId?: string;
    worktreePath?: string;
    replaySnapshot?: string;
    rawReplay?: string;
    at?: number;
};
export declare function createSuspendedPlaceholderSession(input: SuspendedPlaceholderSessionInput): TerminalSession;
export declare function appendTerminalOutput(session: TerminalSession, data: string, at?: number, markAsRealOutput?: boolean): void;
export declare function materializeTerminalReplay(session: TerminalSession): string;
export declare function getTerminalSnapshot(session: TerminalSession): TerminalSessionSnapshot;
/**
 * Event sink for sessions spawned with no window (sprint-runtime-ownership
 * Phase 3: headless scheduler spawns). Every outbound send is guarded on
 * `isDestroyed()`, so a headless session simply emits nothing until a window
 * attaches — the reattach path (`spawnTerminalFromIpc` existing-session
 * branch) then adopts the real WebContents and replays scrollback.
 */
export declare function createHeadlessTerminalSender(): WebContents;
export {};
