import type { IpcMain, WebContents } from 'electron';
import type { AgentCli, AgentExecutionMode, AgentSessionMetadata, CliRuntimeSettings, McpSettings, SprintEngineCliPermissionPreset, TerminalKind, TerminalSessionSnapshot, TerminalSpawnResult } from '../../shared/electron-api';
import type { AgentLaunchRecord } from '../../shared/agent-launch';
export type TerminalSpawnPayload = {
    sessionId: string;
    cols: number;
    rows: number;
    cwd?: string;
    resume?: boolean;
    sprintEngineStatePath?: string;
    cli?: AgentCli;
    initialPrompt?: string;
    cliRuntimes?: Partial<Record<AgentCli, Partial<CliRuntimeSettings>>>;
    shellOnly?: boolean;
    cliSessionId?: string;
    kind?: TerminalKind;
    workspaceId?: string;
    agentId?: string;
    agentName?: string;
    terminalId?: string;
    executionMode?: AgentExecutionMode;
    worktreeId?: string;
    worktreePath?: string;
    cliPermissionPreset?: SprintEngineCliPermissionPreset;
    debugMode?: boolean;
    cliModel?: string;
    cliReasoning?: string;
    memoryRootPath?: string;
    memoryRelativeRoot?: string;
    agentSession?: AgentSessionMetadata;
    visible?: boolean;
    mcpSettings?: McpSettings;
    connectorLaunch?: boolean;
    connectorSkillId?: string;
    spawnSkillId?: string;
    agentRecord?: AgentLaunchRecord;
    metadata?: never;
};
type TerminalIpcDependencies = {
    spawnTerminal(sender: WebContents, payload: TerminalSpawnPayload): Promise<TerminalSpawnResult>;
    writeTerminal(sessionId: string, data: string): void;
    resizeTerminal(sessionId: string, cols: number, rows: number): void;
    getTerminalStatus(sessionId: string, sender?: WebContents): Promise<{
        processAlive: boolean;
        suspended: boolean;
    }>;
    listTerminals(): TerminalSessionSnapshot[];
    setTerminalVisible(sessionId: string, visible: boolean, sender?: WebContents): void;
    suspendTerminal(sessionId: string): void;
    resumeTerminal(sender: WebContents, payload: TerminalSpawnPayload): Promise<TerminalSpawnResult>;
    killTerminal(sessionId: string): void;
    setIdleSuspendThresholdMs(value: unknown): void;
    setKeepRecentTerminalsAlive(value: unknown): void;
    setTerminalReapExempt(sessionId: string, exempt: boolean): void;
    setActiveSprintRunStatePaths(value: unknown): void;
};
export declare function registerTerminalIpc(ipcMain: IpcMain, deps: TerminalIpcDependencies): void;
export {};
